### ISSUE TITLE
Missing install targets

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial/universal_robot#10]
The `CMakeLists.txt` of some packages in the `groovy-dev` branch are missing install targets. This makes it impossible to use them in a install space.

Packages:
- `ur_bringup`
- `ur_description`
- `ur_driver`
- `ur_gazebo`
- `ur_kinematics`

**Comment by ipr-sr2** [comment]
I tiried this, but even without any changes I can find all targets (launch and run files).

**Comment by gavanderhoorn** [comment]
In your install space? I'd be rather surprised, as there are no install statements in any of the `CMakeLists.txt` in any of the above mentioned projects in the `groovy-dev` branch.

**Comment by ipr-sr2** [comment]
they are not in install space, but I meant I can reach them with roslaunch/rosrun commands.

**Comment by gavanderhoorn** [comment]
Sure, but the ticket is about missing _install_ targets, which would result in the files being copied to the install space ..

**Comment by shaun-edwards** [comment]
Merged fix, closing.
