### ISSUE TITLE
Controller read too many bytes for IO message (and possibly others)

### ISSUE THREAD

**Issue by shaun-edwards** [ros-industrial/universal_robot#107]
The program that runs on the UR controller reads too many bytes from the socket connection for setting digital outputs.  See [here](https://github.com/ros-industrial/universal_robot/blob/hydro-devel/ur_driver/prog#L226).  Most times this is not an issue because multiple commands are not typically in the socket buffer (the reference read command only returns the 2 values used for setting digital IO).  However, when trajectories and IO are driven from the ROS side simultaneously (i.e. from multiple threads), this can occur.  When this does, part of the _next_ message in the buffer is read.  This results in several `unrecognized command` messages being reported in the ROS log (although a more critical failure could be misinterpreting the data as a valid command).

I will submit a PR to address this within the week...but I wanted to document it in the near term.

**Comment by fmessmer** [comment]
Is this related to #106?

**Comment by gavanderhoorn** [comment]
Was this also tested on v1.4? I ask because I've had to use some tricks in the past when reading from sockets on older versions of UR's software.

**Comment by shaun-edwards** [comment]
It was discovered on version 1.4, but is clearly a bug on inspection.  I don't think this is related to #106, since the shaking occurs when no commands are sent to the controller.

**Comment by gavanderhoorn** [comment]
``` python
params_mult = socket_read_binary_integer(1+6+1)
```

Ah, you're right. Seems number-of-bytes was specified, instead of number-of-items.

**Comment by shaun-edwards** [comment]
I should have mentioned, I think some of the other byte reads may also have this problem (possibly copy & paste issue)

**Comment by gavanderhoorn** [comment]
It is probably a copy-paste issue: the same sequence of statements is used in the bodies of the other cases (`MSG_MOVEJ` and `MSG_SERVOJ`). Those seem ok though?
