### ISSUE TITLE
driver: analog IO scaling factor is magic nr

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial/universal_robot#109]
As per subject:

``` python
socket_send_int(get_analog_out(0)*1000000)
```

A new `MULT_something` should be added.

**Comment by fmessmer** [comment]
@gavanderhoorn for something as minor as that, could you please send a pull request rather than an issue? you can even do the changes in your browser...

**Comment by gavanderhoorn** [comment]
It was a question of time and effort: I just noticed it, but don't have the time right now to fix it. At least it is now a known issue.
