### ISSUE TITLE
ur5 joint limits

### ISSUE THREAD

**Issue by JessChL** [ros-industrial/universal_robot#112]
Hi, is there a reason for the joint limits being between pi and -pi in the ur5_joint_limited_robot.urdf? The real arm has a range of -2pi and +2pi. This has caused issues for us. Should this be changed?

**Comment by kphawkins** [comment]
The ur5_robot.urdf/ur5_robot.urdf.xacro models use the full 2pi limits. The
reasoning behind using the "limited" model is to improve planning in MoveIt.

**Comment by gavanderhoorn** [comment]
Also, from `README.md`:

> NOTE: As MoveIt! seems to have difficulties with finding plans for the UR with joint limits [-2pi, 2pi], there is a joint_limited version using joint limits [-pi,pi]. In order to use this joint limited version, simply use the launch file arguments 'limited':

**Comment by fmessmer** [comment]
@JessChL 
Do the answers above solve your issue? Or are you still having problem?
If so, please post more details or close this issue!

**Comment by JessChL** [comment]
Thanks for the replies. I am still trying to see how I can overcome having the arm starting in positions outside of the limits other than manually moving the arm, which requires terminating the ur_driver.

**Comment by fmessmer** [comment]
@JessChL 
What do you mean by 

> having the arm starting in positions outside of the limits other than manually moving the arm

For starting up the real UR5 with full joint range [-2_pi, 2_pi] simply use the following command
`roslaunch ur_bringup ur5_bringup.launch robot_ip:=192.168.0.42`
(You might need to adjust the `robot_ip` though)

As long as you are not using MoveIt! you can simply neglect everything related to `joint_limited`

**Comment by JessChL** [comment]
Hi, I am using moveit, and have found the planner really struggle if I don't use the joint_limited urdf. But if we had the robot manually put into a position where one of the joints has absolute value greater than pi, then the robot is "stuck" there unless we shut moveit/ur_driver etc down, move the robot via the pendent, and start everything again. Is that the only solution for now? Thanks.

**Comment by gavanderhoorn** [comment]
What @ipa-fxm means is that the driver shouldn't have any problems controlling the robot, even if it is outside of the [-pi, pi] range (it doesn't care). You could just command it to move the arm into a position that is within the [-pi, pi] range, and only then start using MoveIt.

See `ur_driver/test_move.py` for an example on how to send a `JointTrajectory` without using MoveIt.

**Comment by JessChL** [comment]
Thanks for all the responses!
