### ISSUE TITLE
driver: regression: JointState.effort all zero after merge of #117

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial/universal_robot#125]
As per subject.

**Comment by gavanderhoorn** [comment]
`ur_driver` is deprecated and will not see further development.

Closing.

**Comment by ggupta9777** [comment]
I noticed this recently, getting 0 in all effort fields (ran it for ur5 in gazebo), I was using position interface with join trajectory controller, is it supposed to return 0 for that particular combination? Or is it something specific to this package?

**Comment by gavanderhoorn** [comment]
@ggupta9777 wrote:
> ran it for ur5 in gazebo

`ur_driver` is not used with Gazebo (neither are any of the alternative ROS drivers for URs): the simulation only simulates dynamics, not all controller internals.

**Comment by ggupta9777** [comment]
Sure, I realize that about the driver. Could be that ros_control plugin isn't interested in efforts when using position control with trajectory tracking as it directly commands the joint to move at that place, but was just hoping to get some feedback out of it, not sure how it enforces effort limits in such a scenario.
