### ISSUE TITLE
Connection issues: Waiting to program

### ISSUE THREAD

**Issue by tnl-woi** [ros-industrial/universal_robot#126]
When I start the ur_driver (using `roslaunch ur_bringup ur5_bringup.launch`), the driver does not always start successfully. Sometimes it keeps printing "Waiting to program" repeatedly. Once this happens, the driver is unable to recover and it must be shutdown and restarted.

This was experienced using a UR5 CB3 (software version 3.0).

NB: If a successful connection is closed (this seems to happen when controlling the robot using the Teach Pendant, or after a safety stop), the same happens. I'm not sure if the driver should be able to reconnect in this situation or if this last behavior is intended, for safety reasons. However, during startup (as described above) I think it should definitely be able to connect reliably.

**Comment by gavanderhoorn** [comment]
Just a quick note: the current version of the driver has not been extensively tested with version 3 of the UR controller. I've ran `hydro-devel` against `ursim-3.0` and found that it didn't work very well.

The latest changes merged in (using the rt interface) might have improved this a bit, but I'm not surprised that there may still be some incompatibilities.

**Comment by tnl-woi** [comment]
Just for my understanding, do you have any idea what sort of incompatibilities there are between the versions? Is there any description of the communication protocol anyway? I've seen the packet format, but did not find anything about how to connect to the robot (e.g. how arbitration between the Teach Pendant and an external PC is handled, what to do after a safety stops, how to recover from a broken connection, etc.).

I've taken a quick glance at the ur_driver source code, and had the feeling that this could be caused by a thread synchronization/locking issue in the Python code rather than by a protocol issue.

**Comment by gavanderhoorn** [comment]
I wasn't referring to a specific incompatibility per se, just that I would not be surprised that there would be any, seeing as the current version of the driver has been mostly tested with Polyscope <= 1.8, not 3.

As an example: if you are using `hydro-devel`, the newly introduced deserialiser for the Masterboard data and the real-time client interface could potentially be incompatible with changes in the protocol made by UR. The packet layout tends to change between versions (see their wiki fi: [v3.0](http://wiki03.lynero.net/Technical/PrimaryAndSecondaryClientInterface) and [v1.8](http://wiki03.lynero.net/Technical/PrimaryAndSecondaryClientInterface?rev=24) of the protocol).

See also #123.

**Comment by fmessmer** [comment]
@tnl-woi 
Could you test #135 to see whether the version_aware implementation works for your UR5 with controller version 3.0?

@gavanderhoorn: I knew there was someone with a UR version 3.0 reporting problems wrt deserializeRT :smiley:

**Comment by tnl-woi** [comment]
I'm not sure if the root cause is really fixed or if it's just a side effect, but the driver has started reliably for the last few days, so I think it's an improvement anyway.

But I still don't see how #126 and #135 are related. If anyone cares to explain, that'll be great :)

**Comment by fmessmer** [comment]
Well, `Waiting to program` is printed in case 

```
    def ready_to_program(self):
        return self.robot_state in [self.READY_TO_PROGRAM, self.EXECUTING]
```

returns `false`

So it's likely that the robot_state is not yet set to `READY_TO_PROGRAM` or `EXECUTING`.  
For `READY_TO_PROGRAM`, this can only happen from within the `URConnection` class, i.e. `send_reset_program()` and in [this part of the __on_packet()](https://github.com/ros-industrial/universal_robot/blob/hydro-devel/ur_driver/src/ur_driver/driver.py#L229) which depends of the values of `state.robot_mode_data.robot_mode` which is deserialized from the socket...

Thus, in case there were problems deserializing the protocol for v3.0 before...this might have caused `state.robot_mode_data.robot_mode` not to be in the correct state.

**Comment by abubeck** [comment]
@tnl-woi can we close this issue? If you feel this issue is solved, go ahead and close it yourself.

**Comment by tnl-woi** [comment]
@ipa-fxm Thanks for the additional info. I'm not sure if this really explains it, because state.robot_mode_data.robot_mode is not changed between v1.8 and v3.0. Besides, if it's related to the packet format I think it should always give the same results.
But since it seems to work reliably now, I'll close the issue. If I'll observe the problem again, I'll try to find out what is causing it and open a new issue.

**Comment by gavanderhoorn** [comment]
> Thanks for the additional info. I'm not sure if this really explains it, because state.robot_mode_data.robot_mode is not changed between v1.8 and v3.0. Besides [..]

@tnl-woi: @ipa-fxm is referring to the state machine _internal_ to `driver.py`, not the state of the controller itself.

**Comment by tnl-woi** [comment]
@gavanderhoorn: `self.robot_state` is indeed the internal state of the driver, I assume that's what you are referring to? At first I thought that this state was controlled _only_ by the internal state machine, not by external input from the robot. However, @ipa-fxm pointed out that it also depends on "`state.robot_mode_data.robot_mode` which is deserialized from the socket". However, since this field is not changed between the different firmware versions, I don't understand how adding protocol support for v3.0 affects (i.e. solves) this issue.

My main concern is that `robot_state` is changed by multiple threads, and I have the feeling that the timing between these threads caused the driver to fail sometimes, and that this specific issue is not protocol-related. It's possible that the changes to the driver have changed the timing of the threads, resulting in this improvement. If that's the case the problem is very likely to come back sometime...
