### ISSUE TITLE
Hydro branch...

### ISSUE THREAD

**Issue by ipr-sr2** [ros-industrial/universal_robot#13]
Hello!

I'm trying to automatize installing process for Fraunhofer IPA robots with ROS hydro ([for groovy exists](https://github.com/ipa320/setup.git)). So I forked this repo and [made new hydro-dev branch](https://github.com/ipr-sr2/universal_robot.git), so if you are interested in this please open new branch so I can make pull request and than people will pull things from this (upstream) repo during installation.

Thanks!

**Comment by shaun-edwards** [comment]
@ipr-sr2, I have created a branch.  It's name is slightly different, keeping consistent with other ROS-I branches, hydro-devel.
