### ISSUE TITLE
Issue bringingup ur with new deserializeRT.py

### ISSUE THREAD

**Issue by garyedwards** [ros-industrial/universal_robot#133]
Hi

I am having issues bringing up my UR10 with the new deserializeRT.py.  It seems to fail on the "joint_mode" section at the bottom of the file.  See error log below:

Exception in thread URConnectionRT:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 504, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "/home/gary/catkin_ws/src/universal_robot/ur_driver/src/ur_driver/driver.py", line 370, in __run
    self.__on_packet(packet)
  File "/home/gary/catkin_ws/src/universal_robot/ur_driver/src/ur_driver/driver.py", line 328, in __on_packet
    stateRT = RobotStateRT.unpack(buf)
  File "/home/gary/catkin_ws/src/universal_robot/ur_driver/src/ur_driver/deserializeRT.py", line 114, in unpack
    all_values = list(struct.unpack_from("!dddddd",buf, offset))
error: unpack_from requires a buffer of at least 48 bytes

**Comment by gavanderhoorn** [comment]
Could you provide some more information? What controller type (CB2/CB3), Polyscope version (1.x, 3.x)?

**Comment by fmessmer** [comment]
@garyedwards 
What controllre version are you using? v1.8? v3.0?
This is probably related to #123

**Comment by fmessmer** [comment]
@gavanderhoorn - quicker as always... ;-)

**Comment by garyedwards** [comment]
Hi, thanks for the quick replies and sorry for the lack of information.  I am on CB2UR10 with 1.7.10857, would it be worth upgrading?  Let me know if you need more information.

**Comment by gavanderhoorn** [comment]
@garyedwards: this is due to #123, as @ipa-fxm wrote. The current implementation of the deserialiser in `deserializeRT.py` is only compatible with 1.8.x versions of Polyscope. Updating your controller should let you work around this.

A fix on the driver side (so #123) should make the deserialiser able to unpack data from all supported versions of Polyscope.

**Comment by fmessmer** [comment]
@garyedwards 
Could you test #135 to see whether the version_aware implementation works for your UR10 with controller version 3.0?

**Comment by gavanderhoorn** [comment]
@garyedwards wrote:

> I am on CB2UR10 with 1.7.10857 [..]

@ipa-fxm wrote:

> [..] for your UR10 with controller version 3.0?

?

**Comment by fmessmer** [comment]
Ooops...my mind is swamped with numbers at the moment... :coffee:

**Comment by gavanderhoorn** [comment]
#126 might benefit from this as well.

**Comment by garyedwards** [comment]
@ipa-fxm No problem, I am getting hold of the 1.8 firmware and will report back if this resolves the issue.

**Comment by gavanderhoorn** [comment]
@garyedwards: I think testing with 1.7.x first would be even nicer. 1.8 has been tested, 1.7 hasn't yet.

**Comment by garyedwards** [comment]
Hi the controller I am currently using has been upgraded to 1.8 and I can confirm that it works fine with the UR10 as expected.  I will check to see if any of our other controllers have been left on lower versions and test them when available.  Thanks for your help with this.
