### ISSUE TITLE
ur_driver: no module named deserialize

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial/universal_robot#134]
As reported on ROS Answers: ["ImportError: No module named deserialize" when launching ur5_bringup.launch](http://answers.ros.org/question/196020/importerror-no-module-named-deserialize-when-launching-ur5_bringuplaunch/).

Trying to roslaunch the currently released debs (on Hydro, Precise, 32bit) results in:

``` python
Traceback (most recent call last):
  File "/opt/ros/hydro/lib/ur_driver/driver.py", line 19, in <module>
    from deserialize import RobotState, RobotMode
ImportError: No module named deserialize
```

I'm not sure what is going on exactly. The `ur_driver` pkg has been a 'non-python' catkin package since e05ed9f7 (committed March this year), so it would seem strange if users have only just started running into this.

Trying to execute `ur_driver.py` manually (so not through roslaunch) also results in the traceback.

The `ur_driver` directory _is_ present under `/opt/ros/hydro/lib/python2.7/dist-packages/`, which is what the `$PYTHONPATH` is set to upon sourcing `/opt/ros/hydro/setup.bash`.

**Comment by garyedwards** [comment]
I had this problem with the driver provided by the deb packages.  Adding the ur_driver directory to your python path should be a work around:

export PYTHONPATH=$PYTHONPATH:/opt/ros/hydro/lib/python2.7/dist-packages/ur_driver/

**Comment by gavanderhoorn** [comment]
Right, so this would seem to definitely be a packaging issue then. If everyone using the debs worked around it like @garyedwards did, then this could've been an issue since 1.0.2 was released.

@ipa-fxm: should we perhaps revert e05ed9f for `ur_driver/CMakeLists.txt`? The `ur_driver` Python 'module' containing the files is not correctly being exported anymore. I suspect re-adding the `catkin_python_package()` invocation (and related bits) may help with that.

**Comment by fmessmer** [comment]
This problem does not occur with the current `hydro-devel`
The problem is due to a wrong import missing the parent_module `ur_driver`
It has been fixed in https://github.com/ros-industrial/universal_robot/commit/50cac390f8378345379c6dad4d828638eac3ab69

**Comment by gavanderhoorn** [comment]
Ok, I was unaware of that. Great.

**Comment by gavanderhoorn** [comment]
Closing this then. Should be fixed in next release.
