### ISSUE TITLE
Procedure for bringing Hydro updates to Indigo

### ISSUE THREAD

**Issue by fmessmer** [ros-industrial/universal_robot#137]
There are currently several PullRequests open for Hydro (#128, #131, #135 and #136) as well as Indigo (#130 and #132).  

However, during the review of the Hydro PullRequests some more issues arose that leaded to updates and additional commits. (Some of those are not yet included in #130 and #132).

Still the Indigo PullRequest have been tested and are fine to be accepted.

In order to not get confused with all the various branches for the different features and ROS distributions respectively, I would like to propose the following procedure to bring the remaining (important!) updates from Hydro to Indigo:

After the PullRequests for Hydro (#128, #131, #135 and #136) and Indigo (#130 and #132) have been accepted and merged (as they are), I will compose a single new PR for bringing the remaining features from Hydro to Indigo. This PR will include (typo fixes in the README, material for the collision meshes,  the `max_velocity` parameter handling and the version-aware deserialization).

I hope you can agree to this procdure...

---

Furthermore, I would like to suggest that after this, we trigger new releases for both Hydro and Indigo and then switch the default branch of the repository to `indigo-devel`.

All upcoming new features (like the revision of the IO-Interface) will then only go into indigo-devel.
(Except for Hydro bug-fixes, of course!)

**Comment by shaun-edwards** [comment]
Sounds good to me.

On Friday, October 31, 2014, Felix Messmer notifications@github.com wrote:

> There are currently several PullRequests open for Hydro (#128
> https://github.com/ros-industrial/universal_robot/pull/128, #131
> https://github.com/ros-industrial/universal_robot/pull/131, #135
> https://github.com/ros-industrial/universal_robot/pull/135 and #136
> https://github.com/ros-industrial/universal_robot/pull/136) as well as
> Indigo (#130 https://github.com/ros-industrial/universal_robot/pull/130
> and #132 https://github.com/ros-industrial/universal_robot/pull/132).
> 
> However, during the review of the Hydro PullRequests some more issues
> arose that leaded to updates and additional commits. (Some of those are not
> yet included in #130
> https://github.com/ros-industrial/universal_robot/pull/130 and #132
> https://github.com/ros-industrial/universal_robot/pull/132).
> 
> Still the Indigo PullRequest have been tested and are fine to be accepted.
> 
> In order to not get confused with all the various branches for the
> different features and ROS distributions respectively, I would like to
> propose the following procedure to bring the remaining (important!) updates
> from Hydro to Indigo:
> 
> After the PullRequests for Hydro (#128
> https://github.com/ros-industrial/universal_robot/pull/128, #131
> https://github.com/ros-industrial/universal_robot/pull/131, #135
> https://github.com/ros-industrial/universal_robot/pull/135 and #136
> https://github.com/ros-industrial/universal_robot/pull/136) and Indigo (
> #130 https://github.com/ros-industrial/universal_robot/pull/130 and #132
> https://github.com/ros-industrial/universal_robot/pull/132) have been
> accepted and merged (as they are), I will compose a single new PR for b
> ringing the remaining features from Hydro to Indigo. This PR will include
> (typo fixes in the README, material for the collision meshes, the
> max_velocity parameter handling and the version-aware deserialization).
> 
> ## I hope you can agree to this procdure...
> 
> Furthermore, I would like to suggest that after this, we trigger new
> releases for both Hydro and Indigo and then switch the default branch of
> the repository to indigo-devel.
> 
> All upcoming new features (like the revision of the IO-Interface) will
> then only go into indigo-devel.
> (Except for Hydro bug-fixes, of course!)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ros-industrial/universal_robot/issues/137.

## 

Sent from Gmail Mobile

**Comment by abubeck** [comment]
I completely agree with this procedure as we have also discussed this in person already.

**Comment by fmessmer** [comment]
The respective PR can be found in #138

**Comment by fmessmer** [comment]
New releases have been triggered: 

https://github.com/ros/rosdistro/pull/6188
http://www.ros.org/debbuild/indigo?q=universal_robot

https://github.com/ros/rosdistro/pull/6187
http://www.ros.org/debbuild/hydro?q=universal_robot

Waiting for next sync...l

**Comment by fmessmer** [comment]
Sync is available!
Can we close this issue? @abubeck @shaun-edwards

**Comment by shaun-edwards** [comment]
Close it ;)

**Comment by fmessmer** [comment]
The default branch is still `hydro-devel`

also confirmation for #120 is still missing

**Comment by abubeck** [comment]
I will switch the default branch to indigo-devel. New features will only go into indigo. Bugfixes will be backported of course.
Therefore I will close this issue.
