### ISSUE TITLE
Dependence on pr2_mechanism_diagnostics

### ISSUE THREAD

**Issue by mikepurvis** [ros-industrial/universal_robot#143]
This seems like a very odd dependency for `ur_gazebo` to have. Is this necessary? Do people typically use diagnostics in simulation?

**Comment by fmessmer** [comment]
It's probably a relict from the launch files used for the Care-O-bot that I used as a template...
However, in `indigo_devel` it has been removed... see https://github.com/ros-industrial/universal_robot/commit/6b54b48b1751a107de701035c79ca9e1a24b6952

**Comment by mikepurvis** [comment]
Gone in indigo, sounds good.
