### ISSUE TITLE
Support for v1.4/v1.5 protocol versions?

### ISSUE THREAD

**Issue by fmessmer** [ros-industrial/universal_robot#145]
See discussion [here](https://github.com/ros-industrial/universal_robot/pull/130#issuecomment-61615310)

Link Updated!

**Comment by fmessmer** [comment]
I think we can try to add the parsing of Rev4 linked by @gavanderhoorn ....if it works for v1.4/v1.5...fine!...if not, I suggest to drop support for those versions....

(The ur_driver worked for v1.4 and v1.5 before because the joint_states were send using the custom protocol in `prog` and not the Matlab interface)

**Comment by gavanderhoorn** [comment]
@ipa-fxm wrote:

> See discussion [here](https://github.com/ros-industrial/universal_robot/blob/hydro-devel/ur_driver/src/ur_driver/io_interface.py)

Wrong link?

**Comment by jeppewalther** [comment]
Is there any news on support for 1.5 i have a CB1 arm.

**Comment by gavanderhoorn** [comment]
It has not been re-implemented, but should not actually be too hard: the packet format is documented on the UR wiki. Extending the `RobotStateRT` class in `deserializeRT.py` should be enough to get things working again.

**Comment by jeppewalther** [comment]
I have something working now .. i will submit a pull request.

**Comment by fmessmer** [comment]
see #153 
see #154

**Comment by fmessmer** [comment]
was someone able to test the latest sources on a 1.4?

**Comment by gavanderhoorn** [comment]
@ipa-fxm: I don't have access to a 1.4 platform, and it appears there are also no URSim 1.4 versions. Perhaps it is not too much to ask prospective users to update to _at least_ v1.5 if they want to use the driver?

**Comment by shaun-edwards** [comment]
@Jmeyer1292: Do you know if we have a v1.4 platform?

Generally, I agree with @gavanderhoorn that we should not worry about these older platforms.  If we indeed have v1.4 and the driver does not work with it, we will upgrade (assuming we can).  If not, we could offer a fix.

Presumably @ipa-fxm would want to know for documentation purposes.  For now, we could label it unknown.

**Comment by Jmeyer1292** [comment]
@shaun-edwards We have a 3.0.x and a 1.6.9019 UR5.

**Comment by gavanderhoorn** [comment]
According to @psfafz, the current implementation works with at least 1.5.7849 systems.

v1.4 is probably just too old.

**Comment by abubeck** [comment]
Yes, I agree v1.4 is quite old. As there is no feedback from a v1.4 user, I will close this issue.
