### ISSUE TITLE
arm cannot lift its own weight, will not stay in one position, and flails

### ISSUE THREAD

**Issue by UltronDestroyer** [ros-industrial/universal_robot#146]
I'm not sure what causes this, but using this code here: https://github.com/g/grizzly_ur10/grizzly_ur10_moveit_config and running the demo.launch causes undefined behaviours in the arm.

I get these behaviours regardless of whether or not it's attached to the Grizzly robot. The arm cannot seem to lift its own links either.

**Comment by UltronDestroyer** [comment]
Note: here is the error message for both situations

Controller arm_controller failed with error code PATH_TOLERANCE_VIOLATED
Controller handle arm_controller reports status ABORTED

**Comment by gavanderhoorn** [comment]
And this is in simulation (Gazebo) then right?

**Comment by UltronDestroyer** [comment]
I forgot to add, this is all in simulation.

**Comment by UltronDestroyer** [comment]
Any ideas of what to change? to get this to work?

**Comment by gavanderhoorn** [comment]
Just to be absolutely clear: checking out the `indigo-devel` branch and running `roslaunch ur_gazebo ur10.launch` immediately results in what you describe?

Is the package you linked in any way different from the one in the main repository?

**Comment by UltronDestroyer** [comment]
The package linked has a modified URDF to incorporate a mobile base (The grizzly). It took code from the hydro-devel project of ur10_moveit_config.

Edit: should i be using code from hydro-devel or indigo-devel?

**Comment by gavanderhoorn** [comment]
@TheDash wrote:

> The package linked has a modified URDF to incorporate a mobile base (The grizzly). It took code from the hydro-devel project of ur10_moveit_config.

Could you make sure you see the same behaviour from the `ur_gazebo` package in this repository?

> Edit: should i be using code from hydro-devel or indigo-devel?

At the moment `hydro-devel` and `indigo-devel` should be identical, so it depends on your target environment.

**Comment by UltronDestroyer** [comment]
The hydro-devel package cloned from source does not execute in Gazebo either after running:

roslaunch ur_gazebo ur10.launch
roslaunch ur10_moveit_config demo.launch

It reports using "fake execution" by default. I assumed after turning fake execution off things would be fine, however the arm doesn't respond as you'd expect an arm to. The key files from that package are then used to actuate the grizzly_ur10 package which is the same except the URDF used to generate everything else from the MoveIt assistant is the grizzly + ur10.

The problem is that the arm plans through the grizzly (suspecting that the planner is not assuming the grizzly is a collision) and the arm is unable to lift its own weight so it can point straight up. The arm also sways and is unable to stay in one position. (assuming it's still trying to execute the path) and eventually it gets stuck inside of the grizzly.

**Comment by gavanderhoorn** [comment]
The `demo.launch` file in all MoveIt configuration packages is just that: it is meant to be able to check / demo the configuration pkg, without requiring availability of the real hardware. That does indeed use _fake execution_. All ROS-Industrial MoveIt packages include a `moveit_planning_execution.launch` file which, when supplied with the proper parameters, will allow interaction with real or simulated hardware.

From your description I cannot make out if you followed the instructions layed out in the readme. In particular, the _Usage with Gazebo Simulation_ section.

I agree that this is probably not the cause of the behaviour you are seeing, but it makes sense to first try and see whether the original packages exhibit the same behaviour.

**Comment by UltronDestroyer** [comment]
Thanks! I'll give planning_execution.launch a try, and follow that setup for my package as well, then report back.

**Comment by UltronDestroyer** [comment]
I used the planning_execution setup and that worked.
