### ISSUE TITLE
Wobbling on arm in simulation

### ISSUE THREAD

**Issue by UltronDestroyer** [ros-industrial/universal_robot#147]
This fixes it http://answers.ros.org/question/157261/manipulator-shakeswobbles/. If I made a PR with the changes would it be accepted? I can't see why values that give wobbles should be the default in the repo anyway.

**Comment by shaun-edwards** [comment]
If I understand correctly, the answer requires changing both the inertia and gain values.  I believe the inertia values are based on physical parameters stored in the controller.  If this is the case, then I would be hesitant to change them.  

It also seems odd to adjust inertias to get stable control.  This is not typically a requirement for physical systems, where changing gains is the only option.  Perhaps there is some other issue with the actuator parameters or the simulation itself.

One solution may be to create a "special" gazebo version of the URDF with adjusted inertias.  This would create a patch for those using gazebo while ensuring that others are not affected.

**Comment by UltronDestroyer** [comment]
I agree with the "special". ur10_stable_empty_world.launch?

**Comment by shaun-edwards** [comment]
@ipa-fxm - care to comment/discuss creating a special launch for gazebo (and naming)?

**Comment by fmessmer** [comment]
Sorry for not getting back earlier..._holidays_

I just tested this with the latest releases (1.0.5-0) and I don't see a "wobbling" behaviour when sending FollowJointTrajectories...we fixed this in #86 
Thus we don't need a "special" launch file!

What version are you using? Indigo/Hydro? Debs/Sources?

**Comment by UltronDestroyer** [comment]
Changing the PID values in one of the config files fixed the wobbling.

**Comment by fmessmer** [comment]
@TheDash please close the issue then...
