### ISSUE TITLE
wiki: meta package landing page claims that only Polyscope <= 1.7 has been tested

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial/universal_robot#148]
I don't believe this is still true? Afaik there are several users using the newly released versions with CB3's, which run Polyscope 3.0.x versions, as well as CB2 users running 1.8.x versions.

**Comment by tnl-woi** [comment]
If "has been tested" refers to some sort of formal testing, than I don't know, but indeed I've been using the universal_robot package with a CB3 for some time now :-)

**Comment by gavanderhoorn** [comment]
Just added a _Compatibility_ section to the main metapackage page: [diff](http://wiki.ros.org/action/info/universal_robot?action=diff&rev2=13&rev1=11).

Triggered by #183.
