### ISSUE TITLE
Cannot subsequently execute joint motion and set io through driver

### ISSUE THREAD

**Issue by dpsolomon** [ros-industrial/universal_robot#149]
When
- Any **set io** command is sent to controller after a commanded **joint motion**, or
- Any **joint motion** is sent to controller after a **set io** command,

the pendant shows a fault reading something like "Resizing lists not allowed" and the driver on the PC reports something about "EOF received in response" and loses communication with the controller. Driver must be restarted in order to resume operation.

Tested with ROS Hydro on Ubuntu 12.04 with both _hydro-devel_ and _indigo-devel_ branches on a V3 UR controller.

**Comment by gavanderhoorn** [comment]
Is there any more information? I know the error messages from the UR controller can sometimes be rather vague, but "something like .." is not too specific either :).

Could you perhaps check the log on the controller itself? It should be in the `/root/` directory. Or alternatively, the _log_ tab should also contain the same information (but harder to copy/paste).

Also: in the set_io-after-joint-motion case, is the driver still executing the motion, or is this after the robot has come to a stop again?

**Comment by dpsolomon** [comment]
@gavanderhoorn you're just too fast :) There are some additional details in PR #150. 
I didn't have the controller in front of me when I wrote the issue, and I apologize for the vagueness. I will try to remember to update the wording of the errors when I have the controller again so that we have a good record.

**Comment by dpsolomon** [comment]
Sorry, accidentally closed the issue there for a sec.

**Comment by shaun-edwards** [comment]
These came in over the holidays...pinging to make sure they are seen.

**Comment by tnl-woi** [comment]
I've also seen this error, and took a photograph of it before clicking it away. It is a pop-up window titled "`An error occurred in the running program`" and the exact error message is "`Type error: resizing lists is not supported!`".

**Comment by gavanderhoorn** [comment]
On 5-1-2015 9:34, Wouter van Oijen wrote:

> I've also seen this error, and took a photograph of it before clicking it away. It is a pop-up window titled "`An error occurred in the running program`" and the exact error message is "`Type error: resizing lists is not supported!`".

Ok, great. Thanks.

Could you see whether the changes proposed by @dpsolomon work around this?

**Comment by tnl-woi** [comment]
I'll probably not be able to test these changes. However, the explanation given in #150 is very plausible and the fix looks fine to me. If @dpsolomon has tested this I'm in favor of accepting the pull request. Especially since the I/O interface is unusable in its current state. These changes seem like a big improvement.
