### ISSUE TITLE
No jointstate / minimal tf information

### ISSUE THREAD

**Issue by Lennartm** [ros-industrial/universal_robot#15]
If I run roslaunch ur_gazebo ur5.launch there is no joint_state published (rostopic echo /joint_state). Tf only broadcasts one transform. This makes it difficult to test the arm navigation. I am using gazebo (1.0) on Fuerte, I know this stack is for later versions but this probably there also a problem. 

Also the link: https://kforge.ros.org/login/?returnPath=/ros_industrial/universal_robot redirects to a login page and the project is not in the list.

**Comment by shaun-edwards** [comment]
@Lennartm, I'm not sure what is causing the gazebo issue.  These packages were added after Fuerte.

The link to kforge is probably broken for good.  Everybody has been asked to migrate off of kforge.  We will try to migrate the universal stacks, but this isn't a high priority.  The released versions can still be found in tarballs in the ros dry-release repo, here: https://ros-dry-releases.googlecode.com/svn/download/stacks/universal_robot

**Comment by abubeck** [comment]
As there is no update on this issue, I will close it. Please reopen when you still have this issue.
