### ISSUE TITLE
roslaunch ur5_moveit_config demo.launch not working

### ISSUE THREAD

**Issue by vrabaud** [ros-industrial/universal_robot#152]
With the shadow-fixed version and trunk on Indigo.
(same with UR10). The following collisions appear in the logs which leads to an infinite looping of a planned path:

[ INFO] [1419952994.581014837]: ParallelPlan::solve(): Solution found by one or more threads in 2.137313 seconds
[ERROR] [1419952994.689111360]: Computed path is not valid. Invalid states at index locations: [ 358 359 360 867 868 869 900 901 917 918 ] out of 936. Explanations follow in command line. Contacts are published on /move_group/display_contacts  
[ INFO] [1419952994.689596170]: Found a contact between 'base_link' (type 'Robot link') and 'upper_arm_link' (type 'Robot link'), which constitutes a collision. Contact information is not stored.
[ INFO] [1419952994.689668135]: Collision checking is considered complete (collision was found and 0 contacts are stored)
[ INFO] [1419952994.690282337]: Found a contact between 'upper_arm_link' (type 'Robot link') and 'base_link' (type 'Robot link'), which constitutes a collision. Contact information is not stored.
[ INFO] [1419952994.690321528]: Collision checking is considered complete (collision was found and 0 contacts are stored)
[ INFO] [1419952994.690673467]: Found a contact between 'upper_arm_link' (type 'Robot link') and 'base_link' (type 'Robot link'), which constitutes a collision. Contact information is not stored.
[ INFO] [1419952994.690707776]: Collision checking is considered complete (collision was found and 0 contacts are stored)
[ INFO] [1419952994.691009186]: Found a contact between 'wrist_2_link' (type 'Robot link') and 'upper_arm_link' (type 'Robot link'), which constitutes a collision. Contact information is not stored.
[ INFO] [1419952994.691043014]: Collision checking is considered complete (collision was found and 0 contacts are stored)
[ INFO] [1419952994.691676616]: Found a contact between 'shoulder_link' (type 'Robot link') and 'forearm_link' (type 'Robot link'), which constitutes a collision. Contact information is not stored.
[ INFO] [1419952994.691712401]: Collision checking is considered complete (collision was found and 0 contacts are stored)
[ INFO] [1419952994.692388991]: Found a contact between 'shoulder_link' (type 'Robot link') and 'forearm_link' (type 'Robot link'), which constitutes a collision. Contact information is not stored.
[ INFO] [1419952994.692423658]: Collision checking is considered complete (collision was found and 0 contacts are stored)
[ INFO] [1419952994.693152313]: Found a contact between 'upper_arm_link' (type 'Robot link') and 'wrist_1_link' (type 'Robot link'), which constitutes a collision. Contact information is not stored.
[ INFO] [1419952994.693186975]: Collision checking is considered complete (collision was found and 0 contacts are stored)
[ INFO] [1419952994.693637493]: Found a contact between 'wrist_1_link' (type 'Robot link') and 'upper_arm_link' (type 'Robot link'), which constitutes a collision. Contact information is not stored.
[ INFO] [1419952994.693671122]: Collision checking is considered complete (collision was found and 0 contacts are stored)
[ INFO] [1419952994.694315769]: Found a contact between 'wrist_3_link' (type 'Robot link') and 'upper_arm_link' (type 'Robot link'), which constitutes a collision. Contact information is not stored.
[ INFO] [1419952994.694350590]: Collision checking is considered complete (collision was found and 0 contacts are stored)
[ INFO] [1419952994.694908919]: Found a contact between 'shoulder_link' (type 'Robot link') and 'forearm_link' (type 'Robot link'), which constitutes a collision. Contact information is not stored.
[ INFO] [1419952994.694943801]: Collision checking is considered complete (collision was found and 0 contacts are stored)
[ERROR] [1419952994.695374537]: Completed listing of explanations for invalid states.
[ INFO] [1419952994.711230300]: ABORTED: Motion plan was found but it seems to be invalid (possibly due to postprocessing). Not executing.
QObject::startTimer: QTimer can only be used with threads started with QThread

**Comment by shaun-edwards** [comment]
These came in over the holidays...pinging to make sure they are seen.  We may want to fix this before the next sync.

**Comment by gavanderhoorn** [comment]
@vrabaud: I've tried for some time, but I cannot reproduce this (indigo, x64, `indigo-devel`). I can get some (really) weird paths planned, but they are all valid.

Do you happen to remember whether you started `demo.launch` with `limited:=true`? If not, that might be something to look into.

**Comment by vrabaud** [comment]
Right, I am simply using:

```
roslaunch ur5_moveit_config demo.launch
```

And the version I have is 1.1.5-0trusty-2 on Indigo. With limited:=true, the path is fine indeed. It only loops infinitely with those errors if I do not set this parameter.

**Comment by gavanderhoorn** [comment]
On 5-1-2015 13:47, Vincent Rabaud wrote:

> Right, I am simply using:
> 
> ```
> roslaunch ur5_moveit_config demo.launch
> ```
> 
> And the version I have is 1.1.5-0trusty-2 on Indigo. With limited:=true, the path is fine indeed. It only loops infinitely with those errors if I do not set this parameter.

Ah, ok.

We might have to document the use of the `limited` parameter better, as
people don't seem to read readme's anymore these days :).

**Comment by vrabaud** [comment]
I just used the package, that's it, no README in there :( Maybe you could set that parameter to on by default for now.

**Comment by gavanderhoorn** [comment]
> I just used the package, that's it, no README in there :(

Indeed, `README.md` is only present in the repository root, not in any of the packages. [This](https://github.com/ros-industrial/universal_robot/blob/hydro-devel/README.md) is the file I'm referring to.

> Maybe you could set that parameter to on by default for now.

I'm not actually a maintainer, just another user.

Reasoning behind keeping it `false` by default is that the actual range of all joints of the robot _is_ [-2pi, 2pi]. MoveIt has issues with that, hence the `limited` parameter. Some users have reported problems with uncontrollable robots when `limited:=true` by default, so it has been set to `false`.

**Comment by vrabaud** [comment]
ok ok. Do we have a MoveIt! bug to link to ?

**Comment by gavanderhoorn** [comment]
Not that I know of.

Afaik it's just 'how things are' at the moment (with OMPL/MoveIt). See fi [this](https://groups.google.com/d/msg/moveit-users/_C8ysk6vURg/-osufg4O8fUJ) response by Ioan in [Planning direct path plans](https://groups.google.com/forum/#!topic/moveit-users/_C8ysk6vURg) on the `moveit-users` list.

**Comment by gavanderhoorn** [comment]
For the cases where planning doesn't fail, the resultant paths can get very weird / overly long / complicated, but they are all valid plans. I'm guessing it's just a result of asking a sampling planner to come up with a plan without having a cost-function that allows it to discriminate between 'bad' and 'good' plans.

So any plan is as good as the next one (provided it doesn't violate joint limits / causes a collision).

**Comment by gavanderhoorn** [comment]
@vrabaud: would it be ok to close this as _works-for-me_? Or do you see anything we need to address?

**Comment by vrabaud** [comment]
works for me indeed :) Closing.

**Comment by haixuanwo** [comment]
hello, I met the same problem.
but I can't understand where I should set limited:=true .
my error is not appear in demo.lauch. when I run move_group and use python interface , I get the trouble.

thank for any help advancely
