### ISSUE TITLE
Hydro compatibility of ur_gazebo?

### ISSUE THREAD

**Issue by Lennartm** [ros-industrial/universal_robot#17]
According to the description this stack is for versions above Hydro. But I think the gazebo version is not changed yet. 

The world launch should be changed to:
    `<include file="$(find gazebo_ros)/launch/empty_world.launch" />`

The spawn script should be changed to:

`<node name="spawn_urdf" pkg="gazebo_ros" type="spawn_model" args="-param robot_description -urdf -model ur5" />
`

The plugins should be changed also (investigating that now):

Error [Plugin.hh:127] Failed to load plugin libgazebo_ros_controller_manager.so: libgazebo_ros_controller_manager.so: cannot open shared object file: No such file or directory
Error [Plugin.hh:127] Failed to load plugin libgazebo_ros_power_monitor.so: libgazebo_ros_power_monitor.so: cannot open shared object file: No such file or directory

**Comment by shaun-edwards** [comment]
@Lennartm, I have not created a hydro-devel branch for these changes.  The stack description was confusing.  The repo now follows the ROS-Industrial convention: no master, ros specific version branches(i.e. <version>-devel).  Please submit a pull request against hydro-devel (if you haven't already).

**Comment by fmessmer** [comment]
The hydro-devel branch of ros-industrial/univeral_robot is compatible with latest gazebo and gazebo_controllers since #44 

This issue can be closed!
