### ISSUE TITLE
Re-release of package

### ISSUE THREAD

**Issue by UltronDestroyer** [ros-industrial/universal_robot#194]
Hi UR,

could this package be re-released after adding collisions for the URX arms and the fix to the free-planning joint-free mode?

This would be appreciated as we are currently having to ask people to install source software rather than debs to utilize this package to its full extent.

**Comment by fmessmer** [comment]
The ur_driver currently has some problems when used with latest controller versions (as discussed in other issues)...Thus, the next release will need to wait a bit until things are worked out.

**Comment by fmessmer** [comment]
I'm going to re-release the package....although the issues with the driver still exist...
Still, I think it's worth to have the updates in the `ur_description` as well as in the launch file structure available from debs...

**Comment by fmessmer** [comment]
https://github.com/ros/rosdistro/pull/10950
