### ISSUE TITLE
[C API] hardware_interface/pos_vel_acc_joint_interface.h: No such file or directory

### ISSUE THREAD

**Issue by 2Reeko** [ros-industrial/universal_robot#197]
HI,

I'm using indigo on 14.04 and when I try to catkin_make universal_robot I get the error:

```
[ 96%] Built target ur_sim_server
In file included from /home/anbot/catkin_ws/src/universal_robot/ur_ctrl_client/src/ur_robot_hw.cpp:2:0:
/home/anbot/catkin_ws/src/universal_robot/ur_ctrl_client/include/ur_ctrl_client/ur_robot_hw.h:22:60: fatal error: hardware_interface/pos_vel_acc_joint_interface.h: No such file or directory
 #include "hardware_interface/pos_vel_acc_joint_interface.h"
```

I had a look in hardware_interface and found posvelacc_command_interface.h instead. I was wondering if any of you knew if this is an upgraded version of pos_vel_acc_joint_interface.h or if it would be easier to just install hydro on an earlier version of ubuntu? @kphawkins @shaun-edwards @gavanderhoorn

**Comment by gavanderhoorn** [comment]
Have you solved this? If so, it would be nice if you could tell us how, so we can either do something about it permanently, or at least document this for future users.

**Comment by 2Reeko** [comment]
I changed to the _hydro-devel-c-api_ branch from the _hydro-c-api-ur10-moveit_ branch and made a change to the _ur_controller_iface.cpp_ file. This seems to work because it has _pos_vel_acc_joint_iface_ in _ur_ctrl_client_ instead of in the _hardware_inteface_.
