### ISSUE TITLE
ur5 ForeArm.dae mesh is corrupt

### ISSUE THREAD

**Issue by jrgnicho** [ros-industrial/universal_robot#20]
Invalid character in ForeArm.dae mesh file makes it unreadable under the "UTF-8" character encoding.

**Comment by jrgnicho** [comment]
Tried to fix the mesh with meshlab but it crashes it.
The following error message is shown when openning the mehs file from a browser

XML Parsing Error: not well-formed
Line Number 13511, Column 59:           <rigid_body sid="Actor1-RigidBody" name="UR5-1/Size 1 r\uffffr_r01_Simple-1">
-----------------------------------------------------------------------------------^

**Comment by shaun-edwards** [comment]
Have you tried Blender ( http://www.blender.org/ )?
