### ISSUE TITLE
Gazebo Sim Moves Arm to Crazy Location

### ISSUE THREAD

**Issue by rctoris** [ros-industrial/universal_robot#203]
After updating to the latest indigo release packages (a sycn happened about a day or two ago), the arm now initializes into a crazy position when starting it up. The result is a robot in collision when trying any kind of planning. Here is a video of the launch:

https://www.youtube.com/watch?v=SNTSXciorz4

This happens with both the UR10 and the UR5 with both the normal and joint-limited launches.

**Comment by gavanderhoorn** [comment]
Could this perhaps be related to ros-controls/control_toolbox#40?

**Comment by rctoris** [comment]
Yup, that's the culprit. Using the source version fixes this.
