### ISSUE TITLE
Cannot compile universal robot: URDriverConfig.h error 127

### ISSUE THREAD

**Issue by VictorLamoine** [ros-industrial/universal_robot#230]
```
: No such file or directory
make[2]: *** [/home/dell/catkin_workspace/devel/include/ur_driver/URDriverConfig.h] Error 127
make[1]: *** [universal_robot/ur_driver/CMakeFiles/ur_driver_gencfg.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by VictorLamoine** [comment]
The problem is due the the local git configuration handling of CRLF; switch to
`git config --global core.autocrlf input`

Then re-clone the repository and run `catkin_make` again.

A detailed explanation of the problem is explained [here](http://askubuntu.com/a/372691/73160).
I am just reporting this in case an other user (or the future me) bumps into that issue.

**Comment by gavanderhoorn** [comment]
Just to clarify: this is a client-side configuration option. The sources in the repository are ok.
