### ISSUE TITLE
ERROR: cannot launch node of type [moveit_ros_move_group/move_group]: moveit_ros_move_group

### ISSUE THREAD

**Issue by jacknlliu** [ros-industrial/universal_robot#238]
When I ran the following command:
`roslaunch ur5_moveit_config ur5_moveit_planning_execution.launch sim:=true`  
I got an error:
**ERROR: cannot launch node of type [moveit_ros_move_group/move_group]: moveit_ros_move_group**

**Comment by shaun-edwards** [comment]
Have you downloaded MoveIt?  If you run `roscd moveit_ros_move_group`, does it find the package?

**Comment by jacknlliu** [comment]
`# roscd  moveit_ros_move_group`
`roscd: No such package/stack 'moveit_ros_move_group'`
But I have installed the following packages:

```
ros-indigo-moveit-core   
ros-indigo-moveit-ros-planning  
ros-indigo-moveit-msgs  
ros-indigo-moveit-ros-perception  
```

And `source /opt/ros/indigo/setup.bash` , but it did not work.

**Comment by jacknlliu** [comment]
I should install the full package `ros-indigo-moveit-full`, now it woks! Thank you very much. @shaun-edwards
