### ISSUE TITLE
test_move.py broken in hydro-devel

### ISSUE THREAD

**Issue by gomezc** [ros-industrial/universal_robot#24]
Command "$ roslaunch ur_bringup ur5.launch robot_ip:=..." starts without any error and connects to UR5.

When doing "$ ./test_move.py" roslaunch server replies:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
...
TypeError: Invalid number of arguments, args should be ['positions', 'velocities', 'accelerations', 'effort', 'time_from_start'] args are (...).

**Comment by shaun-edwards** [comment]
Fixed in pull #26
