### ISSUE TITLE
Release into Kinetic

### ISSUE THREAD

**Issue by jonbinney** [ros-industrial/universal_robot#240]
Are there any other packages currently blocking release?

**Comment by pgorczak** [comment]
Looks like MoveIt is blocking  `ur_kinematics`, `ur3_moveit_config`, `ur5_moveit_config` and `ur10_moveit_config`
- http://rosindex.github.io/p/moveit_plugins/#kinetic
- http://rosindex.github.io/p/moveit_ros_planning/#kinetic

Also, `ros-kinetic-gazebo-ros-control` can't be found by my package manager [despite having been released](http://rosindex.github.io/p/gazebo_ros_control/#kinetic) which breaks `ur_gazebo`.

**Comment by gavanderhoorn** [comment]
A kinetic release of MoveIt is close, but still not out. So this remains blocked by that at least unfortunately (ignoring the Gazebo issues @pgorczak mentioned).

**Comment by gavanderhoorn** [comment]
As MoveIt is now available on Kinetic, this is no longer blocked (or at least: not by MoveIt).

**Comment by SimonBirrell** [comment]
Any idea when we can expect a kinetic release?

**Comment by SimonBirrell** [comment]
For those who are also waiting for the Kinetic release, here's how I got it working:

1. Install universal_robot repo into your catkin workspace
2. Add the patch from https://github.com/ros-industrial/universal_robot/pull/254/files
(This is basically adding a few new lines to ur_kinematics/CMakeLists.txt)
3. catkin_make 
4. Install ros-control (this solves the ros-control problem mentioned above by @pgorczak). 

    sudo apt-get install ros-kinetic-ros-control ros-kinetic-ros-controllers

See http://wiki.ros.org/ros_control for more details.

This seemed to do it for me. A deb install for kinetic would still be nice though.

**Comment by shaun-edwards** [comment]
@SimonBirrell, thanks for reporting.  With MoveIt released in kinetic, we can begin releasing ROS-Industrial packages.  Unfortunately, we don't have a timeline for these releases.  We'd welcome an PRs that get's us closer to a release.

**Comment by SimonBirrell** [comment]
The existing pull #254 would get you to where I got.

**Comment by mikaelarguedas** [comment]
Now that #254 got merged (through https://github.com/ros-industrial/universal_robot/pull/286). Is there any other blocker for a kinetic release?

**Comment by davetcoleman** [comment]
I built this locally today and I don't see any blockers for a kinetic release, +1

**Comment by ipa-rmb** [comment]
+1 for releasing

**Comment by AndyZe** [comment]
It builds for me (on Kinetic), but I get this error when running `roslaunch ur_gazebo ur5.launch`. 
`joint_state_controller` was installed by sudo apt install:

> [joint_state_controller_spawner-7] process has died [pid 11838, exit code 1, cmd /opt/ros/kinetic/lib/controller_manager/controller_manager spawn joint_state_controller __name:=joint_state_controller_spawner __log:=/home/nrgadmin/.ros/log/7f8c5b46-76f7-11e7-9269-d07e35252268/joint_state_controller_spawner-7.log].
log file: /home/nrgadmin/.ros/log/7f8c5b46-76f7-11e7-9269-d07e35252268/joint_state_controller_spawner-7*.log
[arm_controller_spawner-8] process has died [pid 11852, exit code 1, cmd /opt/ros/kinetic/lib/controller_manager/controller_manager spawn arm_controller __name:=arm_controller_spawner __log:=/home/nrgadmin/.ros/log/7f8c5b46-76f7-11e7-9269-d07e35252268/arm_controller_spawner-8.log].
log file: /home/nrgadmin/.ros/log/7f8c5b46-76f7-11e7-9269-d07e35252268/arm_controller_spawner-8*.log

**Comment by fmessmer** [comment]
I could trigger the release (I guess, I still have the according access rights :wink:)
However, I have lost proper overview of the functional state of the repo...as it is been a while I was using UR arms...

Could the more active contributors help me get relevant PRs merged and issues closed? @gavanderhoorn 
I will then trigger both tracks - indigo and kinetic

In particular, I see the following relevant:
 - #265, #268, #302 (I guess the proposed changes should also be applied to ur3?)
 - #308 
 - I will also get indigo updates to kinetic #309

**Comment by jacknlliu** [comment]
I think the most import problem is `ur_driver`, fewer people use this repo with latest real UR robot then fewer people use this repository, and then fewer people contribute for this repository. We should know that `ur_modern_driver` is out of the ros industrial. If this repository couldn't work with the latest UR robot, why we do these?

**Comment by fmessmer** [comment]
`ur_driver` has known issues with latest UR HW...(I'm not going to start a discussion about this here)
I just would like to get PRs merged that are already proposed and "approved by discussion" as well as get respective issues closed in order to include them in the next release...

**Comment by fmessmer** [comment]
I'm going to do a release of `kinetic-devel` in order to get the `rosdep` keys out...
another release with missing features/merged PRs can easily be done any time soon...

**Comment by fmessmer** [comment]
releases are:
 - indigo: https://github.com/ros/rosdistro/pull/15686
 - kinetic: https://github.com/ros/rosdistro/pull/15689

**Comment by jonbinney** [comment]
Thanks @ipa-fxm !

**Comment by davetcoleman** [comment]
thanks!

**Comment by gavanderhoorn** [comment]
Closing: the pkgs have been released into Kinetic.

tnx @ipa-fxm for taking the time to do that.
