### ISSUE TITLE
Change material color of gazebo model

### ISSUE THREAD

**Issue by jacknlliu** [ros-industrial/universal_robot#295]
Could we change material color  of gazebo model to make it more like V-REP style, rather than LightGrey for every link?

The UR model in V-REP is more closer to its real color.

**Comment by shaun-edwards** [comment]
Can you provide images of the current and desired robot model?

**Comment by jacknlliu** [comment]
@shaun-edwards  still no available robot model

**Comment by shaun-edwards** [comment]
I mean can you provide an example of the color difference (i.e. the current color in ROS/Gazebo) vs. the desired color in V-REP?

**Comment by jacknlliu** [comment]
@shaun-edwards  I can't get the material color RGB value of UR model from V-REP.  I get a screenshot from V-REP to show the difference.

UR5 V-REP model screenshot:
![UR5 V-REP model screenshot](https://raw.githubusercontent.com/jacknlliu/hello-world/master/resources/ur-vrep.png)

UR5 Gazebo model screenshot:
![UR5 Gazebo model screenshot](https://raw.githubusercontent.com/jacknlliu/hello-world/master/resources/ur-gazebo.png)

**Comment by gavanderhoorn** [comment]
I think this is more a difference in lighting between V-REP and RViz than a difference in material settings.

**Comment by jacknlliu** [comment]
@gavanderhoorn  I don't think it's about lighting.  If you run `roslaunch gazebo_ros rubble_world.launch` , you will find the lighting is the same as UR settings, but the visual effect is different.

**Comment by ipa-nhg** [comment]
Solved by https://github.com/ros-industrial/universal_robot/pull/359
![screenshot from 2018-07-11 10-27-17](https://user-images.githubusercontent.com/650568/42559813-7aecad0e-84f5-11e8-9539-e7b2d5e349ef.png)
