### ISSUE TITLE
Namespace of params for trajectory_execution

### ISSUE THREAD

**Issue by ljmljz** [ros-industrial/universal_robot#307]
The namespace of params 'allowed_execution_duration_scaling' and 'allowed_goal_duration_margin' have moved to trajectory_execution in file trajectory_execution.launch.xml
there is an existing issue for anuc_experimental. please refer the link:[Fix namespace of params for trajectory_execution #24](https://github.com/ros-industrial/fanuc_experimental/pull/24/files)

**Comment by fmessmer** [comment]
this has been fixed for indigo in #285 and will be ported to kinetic in #309

**Comment by fmessmer** [comment]
fixed in #309 by porting #285 to kinetic, too
