### ISSUE TITLE
Unable to move the UR5 using the Universal_Robot stack

### ISSUE THREAD

**Issue by abiudrodas** [ros-industrial/universal_robot#31]
Hi everyone, I have some troubles working with my UR5, I'm trying to work using the Universal_Robot stack, but until today I'm unable to move it. I cloned the Universal_Robot and Industrial_Core stacks into my catkin work space and after to compilation I followed these instructions:

"To check that the package works with a UR5, set up a catkin workspace and clone the repository into the src/ folder. It should look like ~/catkin_ws/src/universal_robot. Don't forget to source the setup file ($ source ~/catkin_ws/devel/setup.*sh), then use catkin_make to compile. You can then start the driver with the following commands (start new terminals, don't forget to source the setup shell files):

$ roslaunch ur_bringup ur5.launch robot_ip:=IP_OF_THE_ROBOT

$ roscd ur_driver; ./test_move.py"

However when I launched the roslaunch ur_bring the calibration offset doesn't work, even though the UR5 is in home position, furthermore, when i execute the test_move script doesn't do anything else that wait for the connection server. 

Somebody knows if I need to do anything else? 

I'm working on ROS hydro, and the software on the Robot is version 1.7.10857.

I leave the screen shots of the process.

Greetings and Thanks in advance. 
![com problem](https://f.cloud.github.com/assets/6050521/1631855/7a5bec7e-576e-11e3-8012-f22c9851ad23.png)

**Comment by shaun-edwards** [comment]
@abiudrodas, Let's handle this on the email list until we know this is a real problem.  If it turns out to be a bug, then we can address it here.

**Comment by jeff-o** [comment]
I am having similar issues in Hydro, I'm running version 1.8.11997 of the Robot Controller.  On one occasion I got an "Invalid number of arguments" error, though the rest of the time nothing was reported.

Was anything resolved via the email list?

**Comment by jeff-o** [comment]
Further information, if it's helpful.  It would appear that position and velocity are being submitted, along with either acceleration or effort (default values?).  However, it is expecting all four:

TypeError: Invalid number of arguments, args should be ['positions', 'velocities', 'accelerations', 'effort', 'time_from_start'] args are([-6.656317565177334e-05, -1.5707761271925431, -0.0001238591293778833, -1.5707761271925431, 0.0, -9.999848021342903e-05], [0.01483342149994571, 0.010590581560890286, -0.010584513618819492, 0.010590581560890286, 0.0, 6.742157856436394e-07], [3.2852830913901334, 2.345585509729385, -2.3442415913701056, 2.345585509729385, 0.0, 0.0001493242621421814], genpy.Duration[4504919])

**Comment by shaun-edwards** [comment]
@jeff-o - As far as I know this was fixed (for software v1.7).  We tried to future proof the problem with those changes as well.  Can you please tell me what version of the software you are using (source, debian, which branch, etc...).

**Comment by jeff-o** [comment]
I'm using the hydro-devel branch.  Installed via the instructions on the github page.

**Comment by jeff-o** [comment]
Perhaps I spoke too soon.  I re-checked which version I'd installed, and I had failed to specify the hydro-devel branch!  The arm moved just fine after that was cleared up.

Sorry for wasting your time!
