### ISSUE TITLE
Add roslaunch testing to pkgs with launch files

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial/universal_robot#314]
Connects: ros-industrial/ros_industrial_issues#11.

roslaunch test cannot test everything (has difficulty with optional args), but it should be added for files it can test.

**Comment by ipa-nhg** [comment]
Solved by https://github.com/ros-industrial/universal_robot/pull/362

**Comment by gavanderhoorn** [comment]
Fixed in #362.
