### ISSUE TITLE
UR5 URDF effort limit

### ISSUE THREAD

**Issue by lth-ml** [ros-industrial/universal_robot#32]
hey,
I am currently using the URDF file of the UR5 robot from this repository for a gazebo simulation. For the simulation I edited the files to use the new controllers from the ros_controllers package (hydro).

Now the problem/question: Why is each joints effort limited to "10"? This doesn't make any sense. With a limit of 10N the robot isn't even able to lift its own weight. I edited this values so I could move the robot properly in the simulation. I am just curious about this number. Why is it limited to 10?

**Comment by shaun-edwards** [comment]
The fact that every joint has the same effort limit is suspect.  One would expect the first few joints to have a larger effort limit than the the wrist joints.

Do you have any documentation supporting a higher joint limit?

**Comment by shaun-edwards** [comment]
@ipa-fmw, @abubeck, Do you have any insight into the effort limit that is in the UR5?

**Comment by kphawkins** [comment]
The maximum torques should be [150, 150, 150, 28, 28, 28] for the UR5.  This can be found by glancing in the /root/.urcontrol/urcontrol.conf directory, finding the "joint_*.conf" files which correspond to the dynamics parameters for each joint motor, then looking at the parameter "torque_max" in each joint configuration file.  Likewise, the max torques for the UR10 should be [330, 330, 150, 54, 54, 54].

**Comment by kphawkins** [comment]
09ef4ead2acaceae9b3b2bfc583346b9238ee537
78b270268fe55abfeed818fb757cd27b474506d5
Fixed urdf files to match these parameters in hydro-devel.

**Comment by shaun-edwards** [comment]
@kphawkins, thanks for the fix, but please submit a pull request next time.  We are now reviewing changes to all dev branches before they are merged (via pull requests).  See http://wiki.ros.org/Industrial/Tutorials/IndustrialPullRequestReview

Sorry to be a pain.

**Comment by shaun-edwards** [comment]
Reviewed...+1
