### ISSUE TITLE
URDF test launch not working

### ISSUE THREAD

**Issue by jacknlliu** [ros-industrial/universal_robot#323]
I run the following launch, but `joint_state_publisher` seems not work, since the rviz not show the robot move.
```
roslaunch  ur_description ur5_upload.launch

roslaunch ur_description test.launch

# then select `world` frame as fixed frame in rviz, add robot state plugin
```

**Comment by gavanderhoorn** [comment]
The "RobotState" display plugin is something from MoveIt.

You'll want to add the "RobotModel" display (scroll down a bit), that will work.

**Comment by jacknlliu** [comment]
thank you very much, it works for me now.
