### ISSUE TITLE
wiki: electric and fuerte pages refer to kforge.ros.org

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial/universal_robot#33]
Just noticed that the [Electric](http://wiki.ros.org/universal_robot?distro=electric) and [Fuerte](http://wiki.ros.org/universal_robot?distro=fuerte) versions of the wiki page of the `universal_robot` stack refers to https://kforge.ros.org/ros_industrial/universal_robot in the _Source_ entry under the _Package Summary_. AFAIK that host has been taken down quite some time ago (or at least: isn't accesible anymore).

Not sure what it should be, or if we can actually change this though.

**Comment by abubeck** [comment]
As we don't really support electric and fuerte actively any more, I would leave it as it is.
@gavanderhoorn : If you agree, please close this issue.

**Comment by fmessmer** [comment]
@gavanderhoorn 
ping?

**Comment by gavanderhoorn** [comment]
We can't update those links without changing the registered `rosdistro` entries, so it's probably best to leave everything as it is.
