### ISSUE TITLE
Controller error trying to interface with CB3/3.40/UR3

### ISSUE THREAD

**Issue by naijoug** [ros-industrial/universal_robot#330]
I use moveit control UR3 real. When planning distance is far, the robot will stop. PolyScope show the error info : "Runtime error: The program used too much time without instructing the robot what to do. Consider using a Wait or sync() to split long program sequences that do not move the robot.".

**Comment by gavanderhoorn** [comment]
Are you using `ur_driver`, or `ur_modern_driver`?

If the first: that is completely unsupported on CB3 controllers.

If the second: please post this issue over at [ur_modern_driver/issues](https://github.com/ThomasTimm/ur_modern_driver/issues).

**Comment by naijoug** [comment]
@gavanderhoorn Thank you.  I use `ur_modern_driver`.  I have already post it.

**Comment by gavanderhoorn** [comment]
In that case that was a cross-post which isn't very nice, but ok.
