### ISSUE TITLE
Next Kinetic Release

### ISSUE THREAD

**Issue by davetcoleman** [ros-industrial/universal_robot#333]
I submitted a PR a few months ago that has not been released to the debian packages yet, can a maintainer please make a new ROS buildfarm release?

**Comment by fmessmer** [comment]
I will trigger new releases for care-o-bot over the weekend anyway, so I don't mind doing it for one more repo - if my permissions are still sufficient :wink:

I will release both indigo and kinetic and merge the following PRs - if I do not get any objections:
 - #312 
 - #322 
 - #329 
 - #332 

@gavanderhoorn @davetcoleman @Levi-Armstrong @shaun-edwards

**Comment by fmessmer** [comment]
I'm trying to release, but https://github.com/ros/catkin/pull/902 keeps messing around which hasn't been released yet...

Installing `catkin` from source helps, but still it doesn't generate and push the tags
It also keeps deleting the content of `ur_description/CHANGELOG.rst`

**Comment by fmessmer** [comment]
There you go:
 - Indigo: https://github.com/ros/rosdistro/pull/16707
 - Kinetic: https://github.com/ros/rosdistro/pull/16708

**Comment by davetcoleman** [comment]
Thanks!
