### ISSUE TITLE
Problem real robot(UR3) error C204A3 when I trying Moveit! execute.

### ISSUE THREAD

**Issue by hj26-park** [ros-industrial/universal_robot#345]
When I trying to moveit! execute with the real UR3 robot, it just work only few second, and then I got a safety Message:
Protective Stop C204A3

I just follow this [tutorial](https://github.com/ThomasTimm/ur_modern_driver), in kinetic 1.12.12.

What's the problem with my robot?

**Comment by gavanderhoorn** [comment]
If you're using `ur_modern_driver`, then please open an issue over at [ThomasTimm/ur_modern_driver/issues](https://github.com/ThomasTimm/ur_modern_driver/issues).
