### ISSUE TITLE
An Error about ur_modern_driver

### ISSUE THREAD

**Issue by Mylszd** [ros-industrial/universal_robot#350]
Hello,I have a problem:

`[ERROR] [1524140921.621973233]: Ignoring transform for child_frame_id "tool0_controller" from authority "unknown_publisher" because of an invalid quaternion in the transform (-nan -nan -nan -nan)`

This error occurred when I operated the actual robot.Please help to solve this.Thanks!

**Comment by gavanderhoorn** [comment]
Please open issues about `ur_modern_driver` on the appropriate issue tracker (ie: the one for `ur_modern_driver`).
