### ISSUE TITLE
description: add support for e-series

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial/universal_robot#369]
As per subject. The e-series robots need to be added, perhaps in a new package (so as to avoid the legacy of the current xacros).

**Comment by davetcoleman** [comment]
Any update on this? Or will UR be releasing their drivers soon?

**Comment by miguelprada** [comment]
See #380 and ros-industrial/ur_modern_driver#216.

**Comment by gavanderhoorn** [comment]
#380 was merged, so I'm going to close this.

**Comment by gavanderhoorn** [comment]
@davetcoleman: robot support packages are independent of the driver used. The new driver will support exporting controller-specific calibration data though, so xacros from the support packages can be updated to correspond 1-to-1 with the actual robot used by a user.

**Comment by davetcoleman** [comment]
Thanks all!
