### ISSUE TITLE
control a UR5 robot arm with Leap Motion or Kinect non-contact sensors in real time in ROS

### ISSUE THREAD

**Issue by stevensu1838** [ros-industrial/universal_robot#379]
Hi team,
I am planning to control a UR5 robot arm with Leap Motion or Kinect non-contact sensors in real time in ROS. I am an absolute beginner. May I please ask how to do that in ROS? Now, I am able be control the UR5 arm very well in Rviz and Gazebo by doing motion planning with Move it. (by following this tutorial http://wiki.ros.org/ur_gazebo)However, what I wanna do is real time teleoperation not first plan the trajectory then execute. Can you please tell me how I can do real time control of UR5 arm in ROS?
secondly, I've noticed in Rivz you can simply drag the tool centre point of UR5 to do the motion planning before execute. Can I only control the tool centre point in the teleoperation to control the whole arm? Coz I only care about the trajectory of the tool centre point. Or I am going have to do mapping for all the joints of the robot to control in real time?
Thanks a lot.

**Comment by gavanderhoorn** [comment]
Thanks for the question, but please ask questions like this on [ROS Answers](http://answers.ros.org).

The issue tracker is for actual issues, and you're asking a much more general "how should I approach this" question.

**Comment by gavanderhoorn** [comment]
I would also recommend to search around a bit (using Google fi: `your keywords site:answers.ros.org` is one example).

You already have the right keywords to search for: `ur5 realtime control`.

This topic has come up quite a nr of times, so you're bound to find some information about it.

**Comment by gavanderhoorn** [comment]
I just noticed [control a UR5 robot arm with Leapmotion or kinect in real time in ROS](https://answers.ros.org/question/301167) that you posted almost simultaneously with this issue.

While ROS Answers is the proper venue for this sort of question, cross-posting like that is not very nice.

At best it leads to split discussions, but it typically results in duplicated (and thus wasted) effort on both sides.
