### ISSUE TITLE
e-series robot models

### ISSUE THREAD

**Issue by adolfo-rt** [ros-industrial/universal_robot#383]
Is there any ongoing effort to support the e-series robots in this repo? The names of the branches seem to indicate that it's not the case, but I wanted to check if somebody has a local branch that I could contribute to / help to test.

**Comment by gavanderhoorn** [comment]
Please see https://github.com/ThomasTimm/ur_modern_driver/issues/184.

So technically the support in a driver will not be part of *this* repository, but the e-series xacro models are being contributed in #380.

> The names of the branches seem to indicate that it's not the case

I'm not sure I understand this comment.

**Comment by adolfo-rt** [comment]
Thanks @gavanderhoorn. Will move any comments to the PR discussion. Closing here.

**Comment by gavanderhoorn** [comment]
Note: #380 only adds urdfs and moveit configs, it doesn't include any driver development or changes.

**Comment by adolfo-rt** [comment]
Fortunately, it's as much as I need at the moment to move forward.
