### ISSUE TITLE
installation in ros melodic

### ISSUE THREAD

**Issue by saied89** [ros-industrial/universal_robot#385]
In [industrial packages documentation](http://wiki.ros.org/Industrial/Install#Binary_Package_Installation_.28Recommended.29) it is stated that universal_robot stack could be installed by 
`apt-get install ros-melodic-universal-robot`
yet apt is unable to find the binary package. 
Is this package released for melodic or I'm missing a ppa or something?
If its not please rectify the documentation.
Also would source installation work in melodic?

**Comment by gavanderhoorn** [comment]
This is an unfortunate side effect of using the `ROS_DISTRO` macro on the wiki. That macro automatically fills in the name of the ROS version selected at the top of the page.

There is no release as of yet for Melodic. Latest release for the packages in this repository is for Kinetic.

I'll see to it that the page gets updated.

You should be able to build the packages from source on Melodic though.

**Comment by saied89** [comment]
Thank you

**Comment by xarthurx** [comment]
@gavanderhoorn 
May I ask which branch should I use for melodic? the kinetic-devel one?

**Comment by gavanderhoorn** [comment]
yes.
