### ISSUE TITLE
Integrate Georgia Tech UR10 urdf with ROS-I version

### ISSUE THREAD

**Issue by shaun-edwards** [ros-industrial/universal_robot#4]
The UR10 URDF created by Georgia Tech (Kelsey Hawkins) is visually more impressive than the current version submitted by Fraunhofer IPA.  The current version is kinematically and dynamically(maybe) correct so the only improvement would be visual.  The UR10 URDF and models can be found here: http://code.google.com/p/gt-ros-pkg/source/browse/?repo=cpl&name=kelsey_sandbox#git%2Funiversal_robot_cpl%2Fur10_description

**Comment by fmessmer** [comment]
I guess this issue can be closed.
The ur_description supports the usage of the Georgia Tech IKFast solver for both arms.
Only UR10 still (or again) uses stl files as visual while UR5 uses dae files.

**Comment by abubeck** [comment]
#83 is also related as it brings in the kinematic plugin.

**Comment by abubeck** [comment]
All in.
