### ISSUE TITLE
How to get another model's collision mesh like "forearm.stl" in ur_description/meshes/collision? 

### ISSUE THREAD

**Issue by langyuxf** [ros-industrial/universal_robot#407]
I have another model, I want get the model's collision mesh. Anyone can describe the details? Using SolidWorks? Thanks

**Comment by gavanderhoorn** [comment]
I don't believe this is related to the packages in this repository.

If your question comes down to "how to make collision models?", then I would like to ask you to post this over at [ROS Answers](http://answers.ros.org).
