### ISSUE TITLE
rviz crashes when trying to launch ur5_moveit_config in hydro

### ISSUE THREAD

**Issue by RobotGod** [ros-industrial/universal_robot#41]
Rviz shuts down immediately after it comes up in hydro with little information about the problem.  Turning on debug gets:
Program received signal SIGSEGV, Segmentation fault. 0x00007fff987983b3 in dynamics_solver::DynamicsSolver::DynamicsSolver(boost::shared_ptr<moveit::core::robotmodel const=""> const&, std::string const&, geometry_msgs::Vector3_std::allocator<void > const&) () from /opt/ros/hydro/lib/libmoveit_dynamics_solver.so

I have found that removing the base_link from the planning group in the setup_assistant makes this function properly.  However this was not necessary in groovy.

**Comment by gavanderhoorn** [comment]
See also [Does anyone have a ur5 working with moveit and hydro?](http://answers.ros.org/question/128566/does-anyone-have-a-ur5-working-with-moveit-and-hydro/) on ROS Answers.

**Comment by fmessmer** [comment]
There is a PullRequest pending that is likely to solve this problem.
#45  brings in newly generated MoveIt! configs using the latest SetupAssistant
