### ISSUE TITLE
Getting Error [Err] [REST.cc:205] Error in REST request

### ISSUE THREAD

**Issue by sapan-ostic** [ros-industrial/universal_robot#412]
Hi, 
I am using ROS Melodic.

I get an error:
[Err] [REST.cc:205] Error in REST request

libcurl: (51) SSL: no alternative certificate subject name matches target host name 'api.ignitionfuel.org'

Also the model looks like:

![Screenshot from 2019-03-23 20-44-10](https://user-images.githubusercontent.com/19823091/54873512-0aa8e580-4dae-11e9-9445-b75fb4ff0ddb.png)

**Comment by gavanderhoorn** [comment]
This has nothing to do with `universal_robot`, but is most likely a Gazebo error (seeing as the Gazebo `api.ignitionfuel.org` host is mentioned).

I would suggest to ask for support over at Gazebo Answers or perhaps even the Gazebo issue tracker.

**Comment by gavanderhoorn** [comment]
I'm closing this (as it's most likely not an issue with the packages in this repository), but if it does turn out to be something we can do something about, please re-open.

Feel free to keep commenting on the issue of course.

**Comment by JonathanPlasse** [comment]
Hi,
Inside `~/.ignition/fuel/config.yaml` replace

`url: https://api.ignitionfuel.org`
by
`url: https://api.ignitionrobotics.org`

It solved the problem for me.

**Comment by gavanderhoorn** [comment]
It's so nice to see Gazebo/Ignition devs/maintainers keeping redirects in place for bw-compatibility ..
