### ISSUE TITLE
 Can this driver connect the arms of the ur e-series?

### ISSUE THREAD

**Issue by wzy19950426** [ros-industrial/universal_robot#421]
I want to use this driver to connect ur5-e,I have replaced the urdf description file in "ur5_bringup.launch".But it doesn't work.I can't get the current pose information of the arm.

**Comment by gavanderhoorn** [comment]
No, `ur_driver` is deprecated, does not see any development any more and should not be used.

See also [wiki/ur_driver](http://wiki.ros.org/ur_driver).
