### ISSUE TITLE
Update MoveIt configurations

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial/universal_robot#430]
Even though the provided MoveIt configurations are only there for convenience and quick testing of new robot setups (ie: right after unboxing) and are not intended for longer use (as any real application would need a customised MoveIt configuration), they should be up-to-date with the latest MoveIt changes.

This includes planner configurations, parameter and launch file names and structure of the package.

Rerunning the MSA and regenerating the packages would be a good first step, but care must be taken to not accidentaly override important configuration or remove settings that are needed for the correct functioning of MoveIt and UR robots.

**Comment by gavanderhoorn** [comment]
Related: #431.

**Comment by jacknlliu** [comment]
@gavanderhoorn just do it, please!

**Comment by gavanderhoorn** [comment]
@jacknlliu: these issues were added in preparation for World ROS-I Day 2019.

Note the `support level: community` in the readme of this repository.

If you participate, perhaps you could even do it!

**Comment by jeritgeorge** [comment]
I can work on this

**Comment by gavanderhoorn** [comment]
@jeritgeorge: nice.

Please first investigate the current layout of the package. There are a few non-standard things that the UR moveit packages have.

It might be insightful to generate a completely new MoveIt configuration in a separate location and then comparing that to the current ones.

**Comment by gavanderhoorn** [comment]
Did you make any progress here @jeritgeorge?

**Comment by jeritgeorge** [comment]
Yes, I've reran the MSA for the ur3 config and went through and compared it to the current one. I think I have a decent understanding of the current setup and should at least have the ur3 config done either tonight or tomorrow. I think once one is done, the rest should be relatively simple.

**Comment by gavanderhoorn** [comment]
I'm going to unassign this @jeritgeorge.

You're welcome to keep working on it of course.

**Comment by fmauch** [comment]
I'l mark this closed, as #538 is merged.
