### ISSUE TITLE
Align MoveIt launch files with other ROS-Industrial packages

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial/universal_robot#431]
The MoveIt packages in this repository use a naming convention that is different from other ROS-Industrial repositories.

This reduces the reusability of experience with other packages and requires users to update launch files whenever using a different robot model.

It would be good to restructure the lauch files such that they conform to conventions used in other repositories (such as Fanuc, ABB and Motoman).

**Comment by gavanderhoorn** [comment]
Related: #430.

**Comment by fmauch** [comment]
This has been included into #538, so this should be good to close.
