### ISSUE TITLE
Cleanup/restructure readme

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial/universal_robot#433]
The current readme should be updated and restructured:

 - installation instructions need to be updated
 - compatibility with different ROS, OS, controller and Polyscope versions need to be made more explicit
 - usage instructions need to be clarified
 - references to `ur_modern_driver` need to be added (including an explanation of when to use it: always, except potentially for CB2 or CB1 controllers)
 - licensing should be made clear (license badges?)

**Comment by gavanderhoorn** [comment]
Related: #367.

**Comment by fmauch** [comment]
Closed via #614
