### ISSUE TITLE
Differences between simulated, theorical and real models

### ISSUE THREAD

**Issue by nicolasCheron** [ros-industrial/universal_robot#455]
Hello,

 I am trying to create a path finder for an UR10 (CB2). I am using PyBullet (it can load an URDF file) and I use the URDF from this package. I have a geometrical model from the DH parameters that are on the Universal Robot website. I have also downloaded the simulation of Polyscope available on the website.
At the end, I have four representations of the UR10:
- The real robot.
- The URDF.
- The Polyscope model.
- The DH model.

The DH and Polyscope models fit perfectly, but I have a 5mm error with the real robot. As I understand, this error is due to the calibration of the robot (DH parameter and joint offsets) and I should be able to solve the difference by digging in the files of the real robot software. Do you have an idea of the file I have to look for ? If this difference is solved, it will be possible to control the robot by sending joint positions. 
My main concern (and the reason I am asking this here), is that I have an error between the DH and URDF models. For the same joint position (0,0,0,0,0,0), I got:
- (-1.183,-0.256,0.0116) for DH.
- (1.183,0.168,0.0116) for URDF. (I have this values with the ros package and gazebo too).

A rotation can fix the sign issue, but how is it possible that there is a 10cm difference on the y axis?
Does someone already face this issue and find a way to solve it?
Thanks for reading

**Comment by gavanderhoorn** [comment]
Please see #414.

**Comment by nicolasCheron** [comment]
Hello, I have seen the other issues but did not find a solution to my problem. The generation of URDF from DH parameters does not seem to be available for the moment. I have read about a yaml file in #414 but did not find it. Is it possible somewhere to do the conversion ?
Thanks

**Comment by gavanderhoorn** [comment]
#414 is to be used with the new driver.

In my opinion it's duplication of effort to do this again, which is why I pointed you to that PR.

The DH parameters are exported also by CB2 robots as far as I know, but that would need to be checked. As soon as you have those, you could use the infrastructure provided by the new driver to generate the `.yaml` file.

Perhaps @fmauch can add something here.

**Comment by fmauch** [comment]
> The DH parameters are exported also by CB2 robots as far as I know, but that would need to be checked. As soon as you have those, you could use the infrastructure provided by the new driver to generate the .yaml file.

Yes exactly. The new driver is just around the corner, probably being released beginning of October.

**Comment by nicolasCheron** [comment]
The matlab code proposed by @cpt-yoshi to create urdf from DH works fine ! I now have an urdf that is at the same pose (error arround 0.1mm), this error is good for my use. 

As I have understood, there is no IK algorithms in the packages that use the closed form of  the robot, the solution returned is the closest from the current position. Some closed form IK solutions for UR are on github but they do not work for calibrated robots with delta's  values in hundreds of meters.

 I implemented a method to calculate DH parameters that are closer from the uncalibrated model than the values of the conf file. With this newly calibrated geometrical model I can perform closed form IK. Are you interested in this work ?

**Comment by gavanderhoorn** [comment]
I'm closing this as it would seem this is addressed by the support for robot calibration data in `ur_robot_driver` and related packages.

If there are still things unclear or not working as they should @nicolasCheron, please re-open on the `ur_robot_driver` issue tracker.

Refer to the [announcement on ROS Discourse](https://discourse.ros.org/t/deprecation-of-ur-modern-driver/11629) for more information on the new driver.
