### ISSUE TITLE
i  want  add a hand on ur arm.but when i use moveit_setup_assisstant  to configure the srdf,the robot can't be dragged.

### ISSUE THREAD

**Issue by XuankeShi** [ros-industrial/universal_robot#463]

**Comment by liang-ry** [comment]
Hi! Did you solve the problem?

**Comment by XuankeShi** [comment]
> Hi! Did you solve the problem?

yes,of course.

**Comment by liang-ry** [comment]
> > Hi! Did you solve the problem?
> 
> yes,of course.

WoW! Happy New year! I have some problomes about the UR5&Robotiq in gazebo, could you give me your contact information？My email is 656686034@qq.com.
Wish you '百毒不侵'！
我最近需要搭建一个UR5+Robotiq的gazebo 仿真平台，非常希望能得到您的帮助！
