### ISSUE TITLE
Make melodic-devel default branch

### ISSUE THREAD

**Issue by davetcoleman** [ros-industrial/universal_robot#475]
Can someone with admin access change the default branch to melodic? Seems to me melodic is no longer the experimental version.

**Comment by gavanderhoorn** [comment]
If with "experimental version" you mean ROS Melodic, then that would be correct.

If you are referring to the state of the `melodic-devel` branch here in this repository, nothing has changed since fi #444. Until #448 is completed, `kinetic-devel` will remain the default branch.

**Comment by gavanderhoorn** [comment]
As this will happen as part of #448, I'll close this one here.
