### ISSUE TITLE
How can I control multiple  ur robot in moveit?

### ISSUE THREAD

**Issue by CaffeMrDe** [ros-industrial/universal_robot#489]
I have a idea about controling multiple  ur robot in a planning scence. But the joint and link on robot is similar ,  there is some diffculty about control them together. How can I deel with it ?

**Comment by gavanderhoorn** [comment]
You would instantiate the macros for your robot models with appropriate values for the `prefix` argument.

That way you can add multiple instances of the same models (and all other variants) to the same xacro.

**Comment by gavanderhoorn** [comment]
As this is a usage / configuration question and not an actual issue with the packages in this repository, I'm going to close the issue.

Feel free to keep commenting on it of course.
