### ISSUE TITLE
Create UR bringup launch files that automatically load joint limited URDFs

### ISSUE THREAD

**Issue by shaun-edwards** [ros-industrial/universal_robot#50]
There are two versions of URDFs for the Universal robots.  The bringup scripts automatically load the URDFs based on a `limited` argument.  If set to true the URDF with limited joint motions (-PI to PI) are loaded.  These joint limits address path planning limitations in MoveIt.

See #44 for more info.

**Comment by fmessmer** [comment]
PullRequest #51 solves this issue!

**Comment by fmessmer** [comment]
Please close this issue as the respective PR has been merged already!

**Comment by floweisshardt** [comment]
solved by https://github.com/ros-industrial/universal_robot/pull/51
