### ISSUE TITLE
Not able to control connected real robot UR3 

### ISSUE THREAD

**Issue by anton-brinster** [ros-industrial/universal_robot#502]
Hey,

I'm using ROS melodic + Ubuntu 18.04.4 LTS.
My goal is to bringup the robot. External control is installed. Robot and Laptop are in the same network using custom port 50001. I'm following the instructions step by step in single terminals, but I can not control the robot at all. I would appreciate any help

roslaunch ur_bringup ur5_bringup.launch robot_ip:=192.168.0.104

> Handling a request
[2020-06-10 19:02:04.221462] Out: hello
[INFO] [1591808524.223433]: Robot connected

roslaunch ur3_moveit_config ur3_moveit_planning_execution.launch 

> ROS_MASTER_URI=http://localhost:11311`
process[move_group-1]: started with pid [9525]
[ INFO] [1591808844.662664675]: Loading robot model 'ur3'...
[ WARN] [1591808844.663925414]: Skipping virtual joint 'fixed_base' because its child frame 'base_link' does not match the URDF frame 'world'
[ INFO] [1591808844.663986500]: No root/virtual joint specified in SRDF. Assuming fixed joint
[ WARN] [1591808844.761382474]: Kinematics solver doesn't support #attempts anymore, but only a timeout.
Please remove the parameter '/robot_description_kinematics/manipulator/kinematics_solver_attempts' from your configuration.
[ INFO] [1591808844.990208142]: Publishing maintained planning scene on 'monitored_planning_scene'
[ INFO] [1591808844.992515684]: MoveGroup debug mode is OFF
Starting planning scene monitors...
[ INFO] [1591808844.992559126]: Starting planning scene monitor
[ INFO] [1591808844.994808938]: Listening to '/planning_scene'
[ INFO] [1591808844.994844680]: Starting world geometry update monitor for collision objects, attached objects, octomap updates.
[ INFO] [1591808844.996687550]: Listening to '/collision_object'
[ INFO] [1591808845.001025634]: Listening to '/planning_scene_world' for planning scene world geometry
[ERROR] [1591808845.002193863]: Failed to find 3D sensor plugin parameters for octomap generation
[ INFO] [1591808845.093663542]: Listening to '/attached_collision_object' for attached collision objects
Planning scene monitors started.
[ INFO] [1591808845.128110706]: Initializing OMPL interface using ROS parameters
[ INFO] [1591808845.152347597]: Using planning interface 'OMPL'
[ INFO] [1591808845.158296617]: Param 'default_workspace_bounds' was not set. Using default value: 10
[ INFO] [1591808845.158922513]: Param 'start_state_max_bounds_error' was set to 0.1
[ INFO] [1591808845.159331987]: Param 'start_state_max_dt' was not set. Using default value: 0.5
[ INFO] [1591808845.159730952]: Param 'start_state_max_dt' was not set. Using default value: 0.5
[ INFO] [1591808845.160134837]: Param 'jiggle_fraction' was set to 0.05
[ INFO] [1591808845.160643858]: Param 'max_sampling_attempts' was not set. Using default value: 100
[ INFO] [1591808845.160752385]: Using planning request adapter 'Add Time Parameterization'
[ INFO] [1591808845.160795111]: Using planning request adapter 'Fix Workspace Bounds'
[ INFO] [1591808845.160833937]: Using planning request adapter 'Fix Start State Bounds'
[ INFO] [1591808845.160894694]: Using planning request adapter 'Fix Start State In Collision'
[ INFO] [1591808845.160937773]: Using planning request adapter 'Fix Start State Path Constraints'
[ WARN] [1591808850.184042290]: Waiting for /follow_joint_trajectory to come up
[ WARN] [1591808856.184386769]: Waiting for /follow_joint_trajectory to come up
[ERROR] [1591808862.184747203]: Action client not connected: /follow_joint_trajectory
[ INFO] [1591808862.195288301]: Returned 0 controllers in list
[ INFO] [1591808862.209989623]: Trajectory execution is managing controllers
Loading 'move_group/ApplyPlanningSceneService'...
Loading 'move_group/ClearOctomapService'...
Loading 'move_group/MoveGroupCartesianPathService'...
Loading 'move_group/MoveGroupExecuteTrajectoryAction'...
Loading 'move_group/MoveGroupGetPlanningSceneService'...
Loading 'move_group/MoveGroupKinematicsService'...
Loading 'move_group/MoveGroupMoveAction'...
Loading 'move_group/MoveGroupPickPlaceAction'...
Loading 'move_group/MoveGroupPlanService'...
Loading 'move_group/MoveGroupQueryPlannersService'...
Loading 'move_group/MoveGroupStateValidationService'...
[ INFO] [1591808862.282895972]: 
...
[ INFO] [1591808862.283012395]: MoveGroup context using planning plugin ompl_interface/OMPLPlanner
[ INFO] [1591808862.283058050]: MoveGroup context initialization complete
You can start planning now!

roslaunch ur3_moveit_config moveit_rviz.launch config:=true

> process[rviz_labor_9561_5085447590804045320-1]:`` started with pid [9576]
[ INFO] [1591809093.889659936]: rviz version 1.13.12
[ INFO] [1591809093.889734857]: compiled against Qt version 5.9.5
[ INFO] [1591809093.889756539]: compiled against OGRE version 1.9.0 (Ghadamon)
[ INFO] [1591809093.895601212]: Forcing OpenGl version 0.
[ INFO] [1591809094.887319986]: Stereo is NOT SUPPORTED
[ INFO] [1591809094.887436028]: OpenGl version: 4.6 (GLSL 4.6).
[ INFO] [1591809098.331354166]: Loading robot model 'ur3'...
[ WARN] [1591809098.331434853]: Skipping virtual joint 'fixed_base' because its child frame 'base_link' does not match the URDF frame 'world'
[ INFO] [1591809098.331474097]: No root/virtual joint specified in SRDF. Assuming fixed joint
[ WARN] [1591809098.409269564]: Kinematics solver doesn't support #attempts anymore, but only a timeout.
Please remove the parameter '/rviz_labor_9561_5085447590804045320/manipulator/kinematics_solver_attempts' from your configuration.
[ INFO] [1591809098.676110935]: Starting planning scene monitor
[ INFO] [1591809098.678989873]: Listening to '/move_group/monitored_planning_scene'
QObject::connect: Cannot queue arguments of type 'QVector<int>'
(Make sure 'QVector<int>' is registered using qRegisterMetaType().)
QObject::connect: Cannot queue arguments of type 'QVector<int>'
(Make sure 'QVector<int>' is registered using qRegisterMetaType().)
[ INFO] [1591809099.010697738]: Constructing new MoveGroup connection for group 'manipulator' in namespace ''
QAbstractItemView::setSelectionModel() failed: Trying to set a selection model, which works on a different model than the view.
QAbstractItemView::setSelectionModel() failed: Trying to set a selection model, which works on a different model than the view.
[ INFO] [1591809100.047311748]: Ready to take commands for planning group manipulator.
[ INFO] [1591809100.047442081]: Looking around: no
[ INFO] [1591809100.047514122]: Replanning: no
[ INFO] [1591809100.057955095]: Marker 'EE:goal_ee_link/10': mesh_use_embedded_materials is ignored.
QAbstractItemView::setSelectionModel() failed: Trying to set a selection model, which works on a different model than the view.

Plan and execute in RVIZ

> [ INFO] [1591809583.271939810]: ABORTED: Solution found but controller failed during execution

> [ INFO] [1591809583.234018216]: Didn't received robot state (joint angles) with recent timestamp within 1 seconds.
Check clock synchronization if your are running ROS across multiple machines!
[ WARN] [1591809583.234153259]: Failed to fetch current robot state.
[ INFO] [1591809583.234377067]: Combined planning and execution request received for MoveGroup action. Forwarding to planning and execution pipeline.
[ INFO] [1591809583.234752268]: Planning attempt 1 of at most 1
[ INFO] [1591809583.237449780]: Planner configuration 'manipulator' will use planner 'geometric::RRTConnect'. Additional configuration parameters will be set when the planner is constructed.
[ INFO] [1591809583.239101969]: RRTConnect: Starting planning with 1 states already in datastructure
[ INFO] [1591809583.239276692]: RRTConnect: Starting planning with 1 states already in datastructure
[ INFO] [1591809583.239388068]: RRTConnect: Starting planning with 1 states already in datastructure
[ INFO] [1591809583.239553366]: RRTConnect: Starting planning with 1 states already in datastructure
[ INFO] [1591809583.251510964]: RRTConnect: Created 4 states (2 start + 2 goal)
[ INFO] [1591809583.251652506]: RRTConnect: Created 4 states (2 start + 2 goal)
[ INFO] [1591809583.251864303]: RRTConnect: Created 4 states (2 start + 2 goal)
[ INFO] [1591809583.252136615]: RRTConnect: Created 5 states (2 start + 3 goal)
[ INFO] [1591809583.252328088]: ParallelPlan::solve(): Solution found by one or more threads in 0.013780 seconds
[ INFO] [1591809583.252676709]: RRTConnect: Starting planning with 1 states already in datastructure
[ INFO] [1591809583.252733711]: RRTConnect: Starting planning with 1 states already in datastructure
[ INFO] [1591809583.252930377]: RRTConnect: Starting planning with 1 states already in datastructure
[ INFO] [1591809583.253086975]: RRTConnect: Starting planning with 1 states already in datastructure
[ INFO] [1591809583.254864234]: RRTConnect: Created 5 states (3 start + 2 goal)
[ INFO] [1591809583.254994181]: RRTConnect: Created 5 states (2 start + 3 goal)
[ INFO] [1591809583.255134289]: RRTConnect: Created 4 states (2 start + 2 goal)
[ INFO] [1591809583.255609333]: RRTConnect: Created 5 states (3 start + 2 goal)
[ INFO] [1591809583.255729832]: ParallelPlan::solve(): Solution found by one or more threads in 0.003134 seconds
[ INFO] [1591809583.255926707]: RRTConnect: Starting planning with 1 states already in datastructure
[ INFO] [1591809583.255983584]: RRTConnect: Starting planning with 1 states already in datastructure
[ INFO] [1591809583.257274858]: RRTConnect: Created 4 states (2 start + 2 goal)
[ INFO] [1591809583.257340332]: RRTConnect: Created 5 states (2 start + 3 goal)
[ INFO] [1591809583.257535619]: ParallelPlan::solve(): Solution found by one or more threads in 0.001645 seconds
[ INFO] [1591809583.261289831]: SimpleSetup: Path simplification took 0.003528 seconds and changed from 3 to 2 states
[ INFO] [1591809583.262094106]: Returned 0 controllers in list
[ERROR] [1591809583.262166789]: Unable to identify any set of controllers that can actuate the specified joints: [ elbow_joint shoulder_lift_joint shoulder_pan_joint wrist_1_joint wrist_2_joint wrist_3_joint ]
[ERROR] [1591809583.262205431]: Known controllers and their joints:
[ERROR] [1591809583.262263201]: Apparently trajectory initialization failed

**Comment by gavanderhoorn** [comment]
You appear to be using a UR3. UR3s only ever came with CB3 controllers, with which you should not be using `ur_driver`.

I'm not surprised this is not working for you.

See also the [wiki/ur_driver](http://wiki.ros.org/ur_driver) page:

> This package has been deprecated and should no longer be used.
> 
> Please see [ur_robot_driver](http://wiki.ros.org/ur_robot_driver) for a replacement.
> 
> Refer to [Deprecation of ur_modern_driver](https://discourse.ros.org/t/deprecation-of-ur-modern-driver/11629) on ROS Discourse for more information. 

So please try with `ur_robot_driver` instead.

However, from this:

> External control is installed. 

I get the impression you already are trying to use `ur_robot_driver`.

In that case, please use the correct launch file, which is in `ur_robot_driver`, *not* in `ur_driver`.
