### ISSUE TITLE
Force/Impedance control of UR e-series

### ISSUE THREAD

**Issue by deepakraina99** [ros-industrial/universal_robot#523]
Is it possible to do cartesian impedance control using ROS for UR e-series? I am able to do with real robot using teach pendant but  I wanted it to do through ROS control? 
If not, do I have force feedback in UR series (in ROS topics) which can be used to write my own impedance controller?

Thanks.

**Comment by gavanderhoorn** [comment]
There is no driver in this repository which you can use, so your question seems like it would be off-topic here.

Please post your question on a more appropriate issue tracker.

**Comment by gavanderhoorn** [comment]
As this is not something which is actionable here for this repository, I'm going to close it.

If you feel this is incorrect, please clarify and we could re-open.
