### ISSUE TITLE
URDF - general question about the rotation about the coordinate frames

### ISSUE THREAD

**Issue by kathrindoerfler** [ros-industrial/universal_robot#534]
Regarding all robot descriptions in this repository: I am trying to understand why the conventions for the location and orientation of all axes of the links and joints in the robot descriptions for the UR robots (both for the e-series and standard series, see Image 1) do not follow the model given by [https://www.universal-robots.com/articles/ur/parameters-for-calculations-of-kinematics-and-dynamics/](https://www.universal-robots.com/articles/ur/parameters-for-calculations-of-kinematics-and-dynamics/)  (see Image 2)?

![ur10e_moveit_screenshot_02](https://user-images.githubusercontent.com/5655420/91749199-6ab9d300-ebc1-11ea-95a0-801ff0f9753f.png)
Image 1: URDF model and coordinate frames visualized in MoveIt of this repo

![images](https://user-images.githubusercontent.com/5655420/91748200-e450c180-ebbf-11ea-9bb3-86f6ff246664.jpg)
Image 2: robot model and coordinate frames as given by Universal Robots

@gavanderhoorn and all, has this been set once and never been changed, or is there a specific reason to why this does not coincide with the model given by UR? It would be great to know the background, and also, whether this could be changed in the future?

Many thanks for your answers!

**Comment by fmauch** [comment]
This is currently changing. The `melodic-devel-staging` branch already contains a version where the frames are more similar to the original approach. However, that seems to cause [problems with other libraries such as kdl](https://answers.ros.org/question/359496/different-axes-of-rotation-arrangement-for-ur5/), so this will probably not be the final stage.

**Comment by gavanderhoorn** [comment]
@kathrindoerfler: could you provide some more insight into what prompted you to post your question?

It's likely you have a specific reason, and it might turn out orientation of those intermediate frames doesn't actually matter (note: the `base` and `tool0` frames correspond to the *Base* feature on the controller and an all-zeros TCP (especially in `melodic-devel-staging`)).

**Comment by gavanderhoorn** [comment]
I'm going to close this due to inactivity.
