### ISSUE TITLE
UR5-e updating polyscop error

### ISSUE THREAD

**Issue by MagnusZaza** [ros-industrial/universal_robot#546]
I'm trying to update Polyscope on UR5-e. When UR5 uses USB to boot, I get the error message saying "Failure reading sector 0x3626a from 'hd0' ". Any idea about this.

Best regards

**Comment by gavanderhoorn** [comment]
I'm afraid this is not a forum for general problems with UR controllers/robots.

Please post your question on the UR support forum instead.
