### ISSUE TITLE
rosrun ur_driver test_move.py  Waiting for server... 

### ISSUE THREAD

**Issue by hariharan382** [ros-industrial/universal_robot#548]
rosrun ur_driver test_move.py
Waiting for server...

i tried as in "https://github.com/ros-industrial/universal_robot/issues/243"
   but could not solve this issue

**Comment by gavanderhoorn** [comment]
Please tell us what version controller you have.

If CB3 or e-Series, use `UniversalRobots/Universal_Robots_ROS_Driver`.

Anything else is **not** supported any more.

**Comment by gavanderhoorn** [comment]
Assuming you actually have a CB3 or e-Series controller, I'm going to close this.

If you have a CB2, you should perhaps try to use `ur_modern_driver`.

In any case, not `ur_driver`, so this is not an issue for this tracker.
