### ISSUE TITLE
unable to find rqt_joint_trajectory_controller in Universal_Robots_ROS_Driver 

### ISSUE THREAD

**Issue by hariharan382** [ros-industrial/universal_robot#551]
to initiate controllers
user:~$rosrun rqt_joint_trajectory_controller rqt_joint_trajectory_controller
[rospack] Error: package 'rqt_joint_trajectory_controller' not found
  

/home/hari/ur10_ws/src/Universal_Robots_ROS_Driver
├── controller_stopper
│   ├── include
│   │   └── controller_stopper
│   └── src
├── ur_calibration
│   ├── include
│   │   └── ur_calibration
│   ├── launch
│   ├── src
│   └── test
├── ur_controllers
│   ├── doc
│   ├── include
│   │   └── ur_controllers
│   └── src
├── ur_dashboard_msgs
│   ├── action
│   ├── msg
│   └── srv
└── ur_robot_driver
    ├── config
    ├── doc
    │   └── initial_setup_images
    ├── include
    │   └── ur_robot_driver
    ├── launch
    ├── resources
    ├── scripts
    ├── src
    └── test
where is rqt folder?

**Comment by gavanderhoorn** [comment]
Please stop opening new issues.

You already have #549 and I've responded there.

Summarising: `rqt_joint_trajectory_controller` is not a part of `Universal_Robots_ROS_Driver`, so I would not expect to find it there.

**Comment by gavanderhoorn** [comment]
I'm closing this, as it's a duplicate (of your own issue).

**Comment by hariharan382** [comment]
so where it is
