### ISSUE TITLE
Ur5 with moveit

### ISSUE THREAD

**Issue by nawrezz** [ros-industrial/universal_robot#567]
is it possible to get the same mouvement as movep with blend radius with moveit?

**Comment by fmauch** [comment]
URScript's `movep` and generating a trajectory using MoveIt is quite different. 

ROS trajectories always go through the specified trajectory setpoints exactly without cutting corners as traditional blending does. Whether the robot will stop in a waypoint or how it will move around the waypoint is determined also by the velocities defined for a waypoint. Waypoints are connected to each other using splines leading to a continuous motion.

As this driver is only executing the trajectories generated by MoveIt! there's not much I can say from a driver's perspective to this. You might want to try asking on ROS Answers, but you should probably describe in more detail what you would actually like to achieve.

**Comment by ipa-nhg** [comment]
@nawrezz could you please give more information? A more elaborated question will be very helpful 

Related post:https://answers.ros.org/question/380628/blend-radius-with-moveitrosur5e/

**Comment by fmauch** [comment]
I'll remove the wrid21 label as this is nothing that can be worked on directly. I'm not sure whether this can be resolved on this level, but to further clarify this, more input would be needed.
