### ISSUE TITLE
How can I execute moveit planning for one of two robots?

### ISSUE THREAD

**Issue by Ryoga723** [ros-industrial/universal_robot#568]
Hello.
I want to control two UR robots.
UR3e by moveit and UR5e by other external program.

In the case for an UR by moveit, I can connect it by beside command. 
roslaunch ur_ros_driver ur3e_bringup.launch
roslaunch ur3_e_moveit_config move_group.launch
And when I can execute moveit program, robot work well .

However,in case for two UR, I can connect two UR robot by group launch.
UR5e is grouped as unit0.Ur3e is grouped as unit1.
And I can connect UR3e to moveit action server.
I designate robot description such as ROBOT_DESCRIPTION = "/unit1/robot_description" in moveit program.

When I execute moveit program, robot doesn't work at all.
There is no error message. 
But Ready to take commands for planning group manipulator message is not shown.

What should I do?
Please help me. Thank you for your advice.

**Comment by gavanderhoorn** [comment]
You seem to be using `ur_robot_driver`. That's good, as that's the only supported driver for e-Series robots.

It also means that your question would be better posted on the [UniversalRobots/Universal_Robots_ROS_Driver/issues](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/issues) tracker.

If/when you do post there, be sure to include more information as "it doesn't work at all" will not be sufficient for the developers of `UniversalRobots/Universal_Robots_ROS_Driver` to help you I believe.
