### ISSUE TITLE
Elbow joint limits just +-pi even with ${joint_limited} false

### ISSUE THREAD

**Issue by vonunwerth** [ros-industrial/universal_robot#577]
Why are the **joint position limits** of the **elbow joint** in each arm description set to `+-pi` even if the `joint_limited` parameter is `false`. Should not they be defined as `+-2pi` regarding the official declarations(https://www.universal-robots.com/media/50880/ur10_bz.pdf) or is that a sort of "trick" to make it easier for moveit to find a IK solution?

```
 <xacro:unless value="${joint_limited}">
        <limit lower="${-pi}" upper="${pi}" effort="150.0" velocity="3.15"/>
```

I can see that there is no reason to turn this joint around its own axis, because it would collide with the robots base, but should the problem already be addressed _at this level_?
If someone really doesn't pay attention to self-collisions, then (for whatever reason) they also want to use the full limits. Considering self-collisions, the limits should then be considered at this level one way or the other.

If you want to address this problem already here, it would also be conceivable to limit the joint further to about **170°** because already then there is a collision with the base.

**Comment by gavanderhoorn** [comment]
Because of #265.
