### ISSUE TITLE
ROS2 Integration

### ISSUE THREAD

**Issue by lydiazoghbi** [ros-industrial/universal_robot#578]
Hi! Are there any plans to translate the contents of this repo to ROS2? Particularly the gazebo scripts.

**Comment by gavanderhoorn** [comment]
ROS 2 work is in [UniversalRobots/Universal_Robots_ROS2_Driver](https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver).

I'm not aware of efforts around the Gazebo packages.
