### ISSUE TITLE
xacro: double underscores are not supported 

### ISSUE THREAD

**Issue by rhaschke** [ros-industrial/universal_robot#582]
Since xacro 1.14.9 (Noetic) or 1.13.13 (Melodic) double underscores in property names are not allowed anymore.
This requires the URDF descriptions to be adapted accordingly. See also https://github.com/ros/xacro/issues/282.

**Comment by rhaschke** [comment]
Looks like underscore names were introduced in the melodic-devel-staging branch only. Thus the Kinetic release isn't yet affected.

**Comment by gavanderhoorn** [comment]
I believe #579 addresses this.

**Comment by rhaschke** [comment]
Thanks for linking this PR. I had the impression that this was already addressed, but I'm surprised that the PR isn't yet merged.
Feel free to close this issue.
