### ISSUE TITLE
description: Should the load_urXX.launch files use the robot-specific macros?

### ISSUE THREAD

**Issue by fmauch** [ros-industrial/universal_robot#585]
As risen in https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/issues/471 the robot model loaded by the `load_urXX.launch` files of `ur_description` create a robot called `ur`:

https://github.com/ros-industrial/universal_robot/blob/0101cae607c9a8e7fc72934849eb4f2343e58ded/ur_description/urdf/ur.xacro#L2

When used with the moveit_config packages (see #538), this name clashes with the SRDF files configured there, when the moveit startup should not re-load the description. It might be a good idea to use the named macros inside the `load_urXX.launch` files.

Is there anything speaking against this?

**Comment by RobertWilbrandt** [comment]
I cannot quite track the intention mentioned in the title, but is this still relevant? As of #538 MoveIt by default doesn't load its own description anymore and #615 made sure that the srdf robot name matches the urdf.

**Comment by fmauch** [comment]
You're right, this should have been resolved by now.
