### ISSUE TITLE
The command to launch simulated robot in README is incorrect

### ISSUE THREAD

**Issue by Jason0-0** [ros-industrial/universal_robot#594]
the command to launch the simulated robot referred in README is
 ` roslaunch ur_gazebo ur5.launch`
However, in the package that I build from the "melodic-devel-staging" branch, it doesn't work and noted that there is not such launch file in ur_gazebo package.
Then I go to the source folder, what I have found is the launch file named "urxx_bringup.launch but not "urx.launch",  so I change the command like this
` roslaunch ur_gazebo ur5_bringup.launch` and it finally works.
![QQ图片20220108212104](https://user-images.githubusercontent.com/49066829/148645809-70fc3b3e-bb59-4954-ba94-21622eec4146.png)

Is that problem only occurs in the branch "melodic-devel-staging" or there is really an incorrect instruction in the README ?

**Comment by fmauch** [comment]
This should probably be fixed on the melodic-devel-staging branch as it was in #538, specifically c3fdfefa93a89e49674439ca44120d4ad80556a5.

**Comment by RobertWilbrandt** [comment]
This is now fixed for some time, so i'll close it. Thank you for the report!
