### ISSUE TITLE
what's the current status of melodic verison and noetic version?

### ISSUE THREAD

**Issue by lianghongzhuo** [ros-industrial/universal_robot#599]
what's the current status of melodic verison and noetic version?

**Comment by fmauch** [comment]
We have been quite busy focusing on the ROS2 release lately. With that converging to a successful first release we will shift some more focus to the ROS1 repositories again.

**Comment by fmauch** [comment]
I'll refer this issue to #448 and more explicitly, the corresponding [milestone 4](https://github.com/ros-industrial/universal_robot/milestone/4).

As they cover pretty much everything that has to be done until the binary release, I'll close this.
