### ISSUE TITLE
Denavit–Hartenberg parameters mismatch for UR10e

### ISSUE THREAD

**Issue by Breakthru** [ros-industrial/universal_robot#600]
Universal Robots publish the DH parameters for their robots on this page:
https://www.universal-robots.com/articles/ur/application-installation/dh-parameters-for-calculations-of-kinematics-and-dynamics/

For some reasons the parameters in the URDF are not the same, they're all just about 1mm different, except for d4 set to 0.135 when the UR webpage shows 0.17415.

https://github.com/ros-industrial/universal_robot/blob/06d8b9e2f5f86aa54f9f2845f11edbc84e2f951e/ur_e_description/urdf/ur10e.urdf.xacro#L58

two questions really:
1) Any reason why the parameters in the xacro are not quite identical to those published by UR?
2) How come d4 is so different?

Many thanks!

**Comment by fmauch** [comment]
The version you've linked seems to be the rather outdated description. We are aware that this is not clearly communicated inside this repository and we are hoping to improve the situation soon (see #599).

For now I would recommend to use the `melodic-devel-staging` branch or my fork's  [calibration_devel](https://github.com/fmauch/universal_robot/tree/calibration_devel) branch when using it together with the `ur_robot_driver`.

**Comment by gavanderhoorn** [comment]
> Any reason why the parameters in the xacro are not quite identical to those published by UR?

because the values in the `xacro:macro` are the values for one particular UR10, and not based on anything published by UR.

I believe it's one of the UR10s of @kphawkins -- from way back in 2012/2013.

**Comment by gavanderhoorn** [comment]
As this doesn't appear to be an issue with the package in this repository, I'm going to close it.

Feel free to keep commenting on it.

If it turns out this is something we need to address here, we'll re-open.
