### ISSUE TITLE
Gazebo not opening

### ISSUE THREAD

**Issue by soumy97** [ros-industrial/universal_robot#601]
Hello,
I am a beginner and I recently downloaded and installed ROS - Noetic in my Ubuntu 20.04 system. Eventually, when I am trying to open the Gazebo simulator by typing gazebo in terminal, this is the error I am getting.

gzclient: symbol lookup error: /lib/x86_64-linux-gnu/libgazebo_gui.so.11: undefined symbol: _ZN17QAbstractItemView11eventFilterEP7QObjectP6QEvent, version Qt_5

What should I do?

**Comment by gavanderhoorn** [comment]
This doesn't seem related to the packages in this repository.

I'd advise you to report this over at [gazebosim/gz-sim](https://github.com/gazebosim/gz-sim) instead.

This issue tracker is for issues with packages related to universal robots only.
