### ISSUE TITLE
Add UR20 support

### ISSUE THREAD

**Issue by fmauch** [ros-industrial/universal_robot#605]
As the [UR20](https://www.universal-robots.com/products/ur20-robot/) has been announced, we should add its description. There are still some (internal) things blocking us from adding it, this issue is meant as a single point of reference whenever the question pops up.

**Comment by garyraise** [comment]
We're hoping to start using the UR20 later this year in our projects. Do you think that support will be added soon?

**Comment by LoyVanBeek** [comment]
What is the status here? 
Is there work-in-progress that I could continue with perhaps? Or otherwise: how to best get started creating the URDF? 

I can probably get the kinematics from the datasheet, but not the meshes of course.

**Comment by RobertWilbrandt** [comment]
Sorry for the late response to the questions. The meshes for the UR20 are not yet publicly available, as soon as they are we will provide patches to add support for them.

**Comment by LoyVanBeek** [comment]
Awesome! And thanks for the quick response to my question :smiley: 

Would it make sense to leave the meshes out on some WIP branch/PR and only have the kinematics in a URDF?

Also: I guess I shouln't hold my breath for those meshes, but is there any estimate on when they'll be available? I'd expect UR to have these soon so people can start trying their stuff out in preparation of buying them, but then they would have been available directly after announcement...

**Comment by urrsk** [comment]
We are working on making this possible. The goal is to have it available in Q3

**Comment by LoyVanBeek** [comment]
Alright, thanks for the update!

**Comment by garyraise** [comment]
Hi all, has there been any update on this? We're planning to replace our UR10s with UR20s and need this driver for that to happen.

**Comment by fmessmer** [comment]
obviously, urdf and meshes are now available via https://github.com/ros-industrial/universal_robot/pull/657

**Comment by urrsk** [comment]
Yes we are getting closer on the ROS side
Everything is now in place in https://github.com/UniversalRobots/Universal_Robots_ROS2_Description and there is a PR for the ROS2 driver as well

**Comment by fmauch** [comment]
Done with #657

**Comment by fmessmer** [comment]
will there be a new release to make the ur20 support available via binaries?

**Comment by fmessmer** [comment]
> will there be a new release to make the ur20 support available via binaries?

thanks @fmauch 
https://github.com/ros/rosdistro/pull/39253
