### ISSUE TITLE
Extract force value from "wrench" topic.

### ISSUE THREAD

**Issue by ZZWang21** [ros-industrial/universal_robot#606]
I would like to extract one of the forces value, for example, force.z, from the rostopic "wrench". I tried many methods, but still not working. I am connecting a real UR5e robot to ROS. I can get the values when using "rostopic echo /wrench". I would like to extract the force.z to use it as a control parameter in python. 

Does any expert have an idea? 

Thank you very much.

**Comment by gavanderhoorn** [comment]
Seems you also opened https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/issues/563, which is a better place to ask this.

Closing.
