### ISSUE TITLE
Gazebo hangs spawning UR5 URDF generated from XACRO.

### ISSUE THREAD

**Issue by b3l33** [ros-industrial/universal_robot#62]
When I attempt to spawn the URDF generated from XACRO (hyrdo-devl), Gazebo hangs and I see an INFO trace indicating that the plugin is waiting on the param server.

> :~/catkin_ws/src/universal_robot/ur_description/urdf$ rosrun gazebo_ros spawn_model -file /home/user/catkin_ws/src/universal_robot/ur_description/urdf/ur5_robot.urdf -urdf -z 1 -model ur5

Console trace:

> [ INFO] [1397671984.537825418, 611.414000000]: gazebo_ros_control plugin is waiting for model URDF in parameter [robot_description] on the ROS param server.

However, if I load the URDF into the param server under the parameter 'robot_description' prior to spawning, the model appears to spawn as expected.

I use the following to load the param server:

```
<launch>
 <param name="robot_description" textfile="$(find ur_description)/urdf/ur5_robot.urdf"/>
</launch>
```

**Comment by fmessmer** [comment]
Well, this behaviour is ok!

The gazebo_ros_control plugin requires information form the URDF to initialize correctly. 
It gets this information from the `/robot_description` parameter.
If you only start gazebo and spawn_model, the parameter has never been loaded to the parameter server. 
However, you can also use your launch file to set the parameter after the model has been spawned already. After setting the parameter the gazebo simulation starts correctly.

Thus, I guess this issue can be closed!

**Comment by fmessmer** [comment]
This launch file will serve your needs:

```
<?xml version="1.0"?>
<launch>
  <param name="robot_description" textfile="$(find ur_description)/urdf/ur5_robot.urdf"/>

  <node name="spawner" pkg="gazebo_ros" type="spawn_model" args="-urdf -param robot_description -z 0.01 -model ur5" respawn="false" output="screen"/>
</launch>
```

**Comment by b3l33** [comment]
Thank you.
