### ISSUE TITLE
Unable to find a random collision free configuration after 100 attempts

### ISSUE THREAD

**Issue by Akumar201** [ros-industrial/universal_robot#630]
### Description

I am trying to use [Moveit servoing tutorial](https://ros-planning.github.io/moveit_tutorials/doc/realtime_servo/realtime_servo_tutorial.html) with pose tracking example.launch. I am trying to move it randomly to  a point to avoid singularity using moveit.rviz . However I am getting the following error no matter how many times I try. 

`Unable to find a random collision free configuration after 100 attempts
`
### Your environment
* ROS Distro: Noetic
* OS Version: e.g. Ubuntu 20.04

### Steps to reproduce

roslaunch ur_gazebo ur5.launch

roslaunch ur5_moveit_config ur5_moveit_planning_execution.launch sim:=true

roslaunch ur5_moveit_config moveit_rviz.launch config:=true

### Expected behaviour
I understand it should avoid planning to be safe , however not taking any random valid path out of many tries is doubtful. There needs to be certain threshold that needs to be set high.

**Comment by gavanderhoorn** [comment]
Could I ask you to please stop cross-posting?

You already have https://github.com/ros-planning/moveit/issues/3339.

I also found a couple of cross-posts from you on ROS Answers.

Pick one venue to post your questions / issues, describe them sufficiently and wait for the maintainer(s) to respond.
