### ISSUE TITLE
 Robot model parameter not found! Did you remap 'robot_description'?

### ISSUE THREAD

**Issue by robot1lyj** [ros-industrial/universal_robot#633]
```
NODES
  /
    move_group (moveit_ros_move_group/move_group)

ROS_MASTER_URI=http://localhost:11311

process[move_group-1]: started with pid [22872]
[ERROR] [1679389175.033983534]: Robot model parameter not found! Did you remap 'robot_description'?
[ERROR] [1679389175.048028912]: Robot model not loaded
[ERROR] [1679389175.053660315]: Planning scene not configured
[move_group-1] process has finished cleanly
log file: /home/lyj/.ros/log/e64b3904-c7b6-11ed-88bc-38baf88de307/move_group-1*.log
all processes on machine have died, roslaunch will exit
shutting down processing monitor...
... shutting down processing monitor complete

```

**Comment by robot1lyj** [comment]
roslaunch ur5_moveit_config moveit_planning_execution.launch

**Comment by MuhammadUmarAnjum** [comment]
Any update on this error?

**Comment by gavanderhoorn** [comment]
I'm not sure I understand exactly what the question is.

The moveit `.launch` files cannot be started in isolation.

The rest (ie: the driver, or gazebo etc) must be started prior to attempting to start moveit.

It would help if @robot1lyj could add a little more information on what (s)he's attempting to do, and how (s)he arrived at the error message.

**Comment by MuhammadUmarAnjum** [comment]
For setting up the MoveIt! nodes to allow motion planning run:
roslaunch ur5_moveit_config moveit_planning_execution.launch sim:=true
For starting up RViz with a configuration including the MoveIt! Motion Planning plugin run:
roslaunch ur5_moveit_config moveit_rviz.launch

These last 2 commands run perfectly but the following 2 gives an error:

roslaunch ur5_moveit_config moveit_planning_execution.launch
roslaunch ur5_moveit_config moveit_rviz.launch

ALthough the last two commands are sufficient for running the the moveit and gazebo simulation, I think not 100% sure.
