### ISSUE TITLE
How to get the raw value of force_torque_sensor?

### ISSUE THREAD

**Issue by KentoYamamotoNU** [ros-industrial/universal_robot#637]
I am using a robot hand (2F-85) from robotiq attached to UR. When UR is started, the value of force_torque_sensor is initialized and the force shown in the /wrench topic is the picture below. ![image1](https://github.com/ros-industrial/universal_robot/assets/104415346/c352e8dc-b78e-48d3-a913-8def33eb6d86)
The posture at this time is the picture below. 
![image0](https://github.com/ros-industrial/universal_robot/assets/104415346/2d1e4106-56cc-4ca8-bf91-fdab6d361fba)
The value of force_sensor is corrected and the value changes as shown in the picture below about 3 minutes later, even though UR is not moved. 
![image6](https://github.com/ros-industrial/universal_robot/assets/104415346/42171fa4-770b-45b2-bcaf-daef3149d3aa)
Also, if the robot hand was rotated 90 degrees around the x-axis and the y and z values will be different, as shown in the picture below. 
![image2](https://github.com/ros-industrial/universal_robot/assets/104415346/274880e7-6ccf-4ba4-ab0e-d4d601fa1c97)
![image3](https://github.com/ros-industrial/universal_robot/assets/104415346/f6ae0a0c-7fff-4a2f-9220-0f3de013b8df)
How can I get the raw data of force_torque_sensor without any correction?

**Comment by gavanderhoorn** [comment]
I would assume you are using either [UniversalRobots/Universal_Robots_ROS_Driver](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver) or the ROS 2 version of that driver.

In any case I'd suggest to post your question there, as we don't support that driver here.

If you do post your question on `UniversalRobots/Universal_Robots_ROS_Driver`: please don't post screenshots/photos of terminals. Just copy-paste the text from the terminal into your question.

**Comment by KentoYamamotoNU** [comment]
Thanks for the replies and advice. I reposted it in UniversalRobots/Universal_Robots_ROS_Driver.
