### ISSUE TITLE
Add robitq 85 gripper to UR10

### ISSUE THREAD

**Issue by qdl49** [ros-industrial/universal_robot#639]
Hello, I'm new to ROS and I'm trying to add a robotiq 85 gripper to UR10. When I add it at the end of ur_macro.xacro, nothing happens. Do you know what is the problem ?

Thank you.

**Comment by Southyang** [comment]
Hello, how did you solve this problem? When I want to add robotiq 85 2f to the robot of ur5, I also find that it cannot be displayed.
