### ISSUE TITLE
Joint 'erver' not found in model 'ur5_robot' error in moveit when using compute_cartesian_path

### ISSUE THREAD

**Issue by devvaibhav455** [ros-industrial/universal_robot#640]
Hi,

System details: Ubuntu 20.04 on amd64 architecture with ROS noetic

I am trying to simulate a UR5 robot in gazebo and want the EE to follow a cartesian goal in real-time. I subscribe to a topic which continuously publishes 6-DOF pose and then I use `compute_cartesian_path`. It works most of the times but sometimes I get these errors.

Error # 1:
`SimpleSetup: Path simplification took 0.001818 seconds and changed from 3 to 2 states`
`[ INFO] [1686337081.111904271, 6693.901000000]: Attempting to follow 1 waypoints for link 'tool0' using a step of 0.050000 m and jump threshold 0.000000 (in global reference frame)`
`[ INFO] [1686337081.117172171, 6693.906000000]: Computed Cartesian path with 2 points (followed 100.000000% of requested trajectory)`
`[ INFO] [1686337081.117837855, 6693.907000000]: Execution request received`
`[ERROR] [1686337081.119268921, 6693.908000000]: Joint 'erver' not found in model 'ur5_robot'`
`[move_group-1] process has died [pid 1328127, exit code -11, cmd /opt/ros/noetic/lib/moveit_ros_move_group/move_group /scaled_pos_joint_traj_controller/follow_joint_trajectory:=/eff_joint_traj_controller/follow_joint_trajectory __name:=move_group __log:=/home/dev/.ros/log/62d75aac-06e6-11ee-9fd9-b5f2b2fb5025/move_group-1.log].`
`log file: /home/dev/.ros/log/62d75aac-06e6-11ee-9fd9-b5f2b2fb5025/move_group-1*.log`

Error # 2:
`Execution request received`
`[ERROR] [1686340497.445277228, 10104.988000000]: Joint '??
                                                          ?' not found in model 'ur5_robot'`
`[move_group-1] process has died [pid 1802270, exit code -11, cmd /opt/ros/noetic/lib/moveit_ros_move_group/move_group /scaled_pos_joint_traj_controller/follow_joint_trajectory:=/eff_joint_traj_controller/follow_joint_trajectory __name:=move_group __log:=/home/dev/.ros/log/62d75aac-06e6-11ee-9fd9-b5f2b2fb5025/move_group-1.log].`
`log file: /home/dev/.ros/log/62d75aac-06e6-11ee-9fd9-b5f2b2fb5025/move_group-1*.log`

I use the below commands to run the simulation and move it.

In terminal 1:
`roslaunch ur_gazebo ur5_bringup.launch`

in terminal 2:
`roslaunch ur5_moveit_config moveit_planning_execution.launch sim:=true`

Thanks in advance for your help.

**Comment by gavanderhoorn** [comment]
This looks like a problem in `move_group`: `-11` is a segfault, which implies memory corruption or ABI compatibility problems.

The fact you see `erver` and `??` as joint names makes me very suspicious, as those are clearly not proper names.

I'm going to close this here, as it's not a problem with the packages here -- as far as I can tell right now. I'd suggest posting on the MoveIt issue tracker instead.
