### ISSUE TITLE
UR5 Wobbles when fixed to world/ground

### ISSUE THREAD

**Issue by b3l33** [ros-industrial/universal_robot#68]
I am using the UR5 in Gazebo fixed to the ground (and/or fixed to a cylinder fixed to the ground). When doing so, the model wobbles a lot. (The wobbling fades as time goes by.) Is this correct behaviour? Or is it related to rigidly fixing it to the ground? Is there anything I can do to stabilize the simulated model.

```
<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="cr_ur5_mounted" >

  <xacro:include filename="$(find ur_description)/urdf/gazebo.urdf.xacro" />
  <xacro:include filename="$(find ur_description)/urdf/ur5.urdf.xacro" />

  <xacro:ur5_robot prefix=""/>

  <link name="world"/>

  <joint name="grouding" type="fixed">
    <parent link="world"/>
    <child link="base_link"/>
  </joint>

</robot>

```

**Comment by fmessmer** [comment]
What do you mean with "wobbling"?
Is the whole robot flying through the air or are only the joints slightly oscillating?
(For me it was the second case)
This comes from the fact that probably the physics of the robot (inertia, damping, friction,...) and/or the controller parameters are not perfectly correct/optimal. They might need some more fine-tuning. You can read more about this in the Gazebo tutorial: 
http://gazebosim.org/wiki/Tutorials/1.9/ROS_Control_with_Gazebo

Can you move the robot at all? How are you sending commands?

**Comment by javanegmond** [comment]
Did you load the gazebo empty_world? empty_world contains a ground plane with collision enabled. The default position of the ur5 has the arm intersecting with said ground plane, which in my case caused 'wobbling' as well as unpredictable control results.
Could you load the robot at an offset, for instance by including command line arguments on the robot spawner? In the ur5.launch file, change the relevant line to something like this:

```
 <node name="spawn_gazebo_model" pkg="gazebo_ros" type="spawn_model" args="-urdf -param robot_description -model robot -z 1.0 -x 0.0 -y -0.0" respawn="false" output="screen" />
```

to see if the ground plane collision is causing the problem.

**Comment by b3l33** [comment]
Thank you for your responses. This is proving to be a great community....

Please find the video I posted on youtube for visual reference:

http://youtu.be/RVYIK4C_mgk

@ipa-fxm - Thank you for the link - I have been using that to get to where I am so far with my project... I am driving Gazebo with MoveIt! using the the moveit config provided with the universal_robot package. I am using a version of demo.launch that has been modified to use the xacro defined in the original post as well as with the move_group argument 'fake_execution' changed to 'false':

```
  <include file="$(find ur5_moveit_config)/launch/move_group.launch">
    <arg name="allow_trajectory_execution" value="true"/>
    <arg name="fake_execution" value="false"/>
    <arg name="info" value="true"/>
    <arg name="debug" value="$(arg debug)"/>
  </include>
```

@javanegmond - Affirmative: I am using /universal_robot/ur_gazebo/launch/ur5.launch. I have noticed that the wobbling behaviour exists even when the model is not fixed to the ground but appears damped due to contact with the ground. I did as you suggested. This just results in the a different pose and flopping about a bit (nothing as bad as some models when dropped from high above the ground (e.g., z > 2.0)). At any rate, I don't believe that spawning with intersection with the ground plane is the issue in this particular case.

So is it safe to assume that the wobbling behaviour is typical "out of the box" for this package? I am trying to eliminate any problems I may be introducing. 

If it is due to the way the this package is configured, are there any suggestions to improve the stability of the model?

**Comment by b3l33** [comment]
I am cross posting a very helpful response from ros.org. While not perfect it is a great improvement.

http://answers.ros.org/question/157261/manipulator-shakeswobbles/?answer=157976#post-id-157976
