### ISSUE TITLE
Verify LinkLengths

### ISSUE THREAD

**Issue by fmessmer** [ros-industrial/universal_robot#74]
I opened this issue in order to record the discussion on the mailinglist on github as well:
https://groups.google.com/forum/#!topic/swri-ros-pkg-dev/1e3A_1BTQWQ

**Comment by fmessmer** [comment]
@gavanderhoorn, @kphawkins

**Comment by fmessmer** [comment]
As this is probably the most related issue:
In https://groups.google.com/forum/#!topic/swri-ros-pkg-dev/5KBACyQNJro a discussion came up about what the currect velocity and acceleration limits for the joints are.

Can someone verify these values?

For the record: @paturdc

**Comment by fmessmer** [comment]
the velocity issue can be discussed in a separate issue #76

**Comment by de-vri-es** [comment]
I talked to Kelsey Hawkings about the ur_kinematics parameters. Those values were taken from configuration files of the robot controller (I also double checked them for the UR5, they match), so they are probably better than the values from the drawing. UR seems to think so anyway.

That means that there is no issue with the ur_kinematics DH parameters, but the link lengths in the UR10 URDF still seem to be wrong. Does anyone know who to contact about those?

**Comment by abubeck** [comment]
I contacted someone at UR already. I'm still waiting for a reply.

**Comment by gavanderhoorn** [comment]
So did you ever get a reply from UR?

**Comment by abubeck** [comment]
Yes. According to UR the correct link length are in the config file of the UR. @ipa-fxm checked the link length to the configs on all our controllers (UR10 and UR5) and verified them with the current PR's. That means once we have all current urdf PR's in, the link length should be fine.

**Comment by gavanderhoorn** [comment]
So for all robots (of the same model), the link lengths are the same? There is no variation in the link lengths between my UR5 and yours (so to say)?

**Comment by abubeck** [comment]
We didn't notice any variation.
