### ISSUE TITLE
Verify Velocity/Acceleration limits

### ISSUE THREAD

**Issue by fmessmer** [ros-industrial/universal_robot#76]
Maybe a separate issue for this is better...

**Comment by fmessmer** [comment]
In https://groups.google.com/forum/#!topic/swri-ros-pkg-dev/5KBACyQNJro a discussion came up about what the currect velocity and acceleration limits for the joints are.

Can someone verify these values?

For the record: @paturdc

**Comment by fmessmer** [comment]
There is also a default value for max_velocity set in the ur_driver.py (https://github.com/ros-industrial/universal_robot/blob/hydro-devel/ur_driver/src/ur_driver/driver.py#L680).
The default value there is not the same as the one set in the URDF and the actual parameter is set nowhere so that it actually uses the default value given in ur_driver. 
This leads to problems when MoveIt! generates trajectories based on the URDF velocity limits that are to be executed on the controller.

**Comment by abubeck** [comment]
As we use the max_vels from the urcontrol.conf now I will close this issue.

**Comment by gavanderhoorn** [comment]
Should the fact that the acceleration limits are not used be documented somewhere?

**Comment by abubeck** [comment]
It is now documented by your comment :smile:

**Comment by gavanderhoorn** [comment]
I get the smiley, but my question was serious :). I think it would be good to document this somewhere, as it will not be clear from the xacro/urdf itself why the acceleration limits are not as they are in the actual control system.

I've already seen (and received) questions about the portability of results obtained in simulation to a real world scenario, and I think that deviations from values found in the official source(s) should be documented, as they can influence the dynamic behaviour of the simulation (and thus the results).
