### ISSUE TITLE
driver: published WrenchStamped msg does not set frame name

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial/universal_robot#80]
The recently merged `WrenchStamped` publisher [does not](https://github.com/ros-industrial/universal_robot/blob/f003b5cd0f4ff9e8767e3b2d2fe4150f84b6943a/ur_driver/src/ur_driver/driver.py#L308-L322) seem to initialise the _header.frame_ field to any value. The scripting manual (v1.8, aug 2013) of the UR says:

> **get_tcp_force()**
> [..]
> The function returns ”p[Fx (N), Fy(N), Fz(N), TRx (Nm), TRy (Nm), TRz (Nm)]”. where Fx, Fy, and Fx are the forces in the axes of the robot base coordinate system measured in Newtons, and TRx, TRy, and TRz are the torques around these axes measyred in Newton times Meters.

(sic).

If done on purpose (not setting the frame name), then this should probably be documented. Otherwise, the correct frame should be set by the publisher.

**Comment by gavanderhoorn** [comment]
Ping

**Comment by abubeck** [comment]
We will work on this during merging of PR #78, but we want to wait until #92 is merged (tests pending).

**Comment by fmessmer** [comment]
@Equanox @gavanderhoorn 
Is it correct that the `robot base coordinate system` is `${prefix}base_link` in our case?

**Comment by gavanderhoorn** [comment]
yes, well, sort of. See ros-industrial/ros_industrial_issues#24 for some discussion.

The UR urdfs don't have the additional `base` link yet (#95), which means that `base_link` does not necessarily have the correct orientation wrt the real robot. Setting `base_link` as the `header.frame` link would then not work (I think).

@abubeck and @ipa-fmw should recognise this. See also [this](https://groups.google.com/forum/#!topic/swri-ros-pkg-dev/WHbKhHjn_AM) discussion on the ROS-Industrial mailing list about it.

I have seen some discussion with UR about this, but I don't know whether we have been able to resolve this yet.

**Comment by gavanderhoorn** [comment]
@ipa-fxm wrote:

> Is it correct that the `robot base coordinate system` is `${prefix}base_link` in our case?

As #200 has been merged, we should now be able to consider `${prefix}_base` as the `robot base coordinate system`.

**Comment by gavanderhoorn** [comment]
`ur_driver` is deprecated and will not see further development.

Closing.
