### ISSUE TITLE
Safety stop issued from controller when full acceleration allowed

### ISSUE THREAD

**Issue by shaun-edwards** [ros-industrial/universal_robot#89]
The default moveit acceleration values in the move config packages ([here](https://github.com/ros-industrial/universal_robot/blob/hydro-devel/ur5_moveit_config/config/joint_limits.yaml)) do not allow the universal to reach full speed (even in very long moves).  Some limited testing shows that increasing the allowed acceleration results in much faster motion.  However, safety stops result at higher acceleration limits (10 x current values).  

Has anybody encountered this, and if so, Is there a way to address this issue, as the current acceleration values result in very slow motion?

**Comment by gavanderhoorn** [comment]
See also #67.

**Comment by gavanderhoorn** [comment]
The current accel limits do not come from the relevant files on the controller (see [this](https://github.com/ros-industrial/universal_robot/pull/84#issuecomment-51086250) comment by @ipa-fxm on PR84). So I can imagine they limit the UR.

> However, safety stops result at higher acceleration limits (10 x current values).

Is this with proper TCP payload (and CoG) settings?

**Comment by fmessmer** [comment]
As was mentioned already, the accel limits currently used are not the ones from the urcontrol.conf
However, as @shaun-edwards is now telling, 10 x current values leads to safety stop behaviour.
The real values in the urcontrol.conf were about this magnitude or even higher...
So what values should be used then to not limit the UR but also not lead to safety stop behaviour?

**Comment by shaun-edwards** [comment]
I've found that the under the current control scheme the max acceleration values are around 5 rad/s^2.  At this acceleration, the robot rarely, if ever, reaches full speed.  It spends most of a trajectory accelerating or decelerating.

I've done some further experimenting (I'm capturing the data here for others).  All of the following refers to the UR5 with software version 1.4.
- Dense trajectories result in slower motion.  I have verified this using standard teach pendant program.  This is a known/typical limitation of robot controllers (not just universal).  The current driver (PC side) interpolates any trajectory resulting in a dense trajectory.  I've reworked the driver to only send the points in the trajectory.  With this driver, I have been able to achieve high speeds with sparse trajectories.
- The current driver uses the URScript _servoj_ command.  For experimentation purposes, I used the _movej_ command.  This command blocks until motion completes making it easier to implement the controller side of the driver.  It's not clear whether utilizing this command made a difference in motion.  The modified driver, utilizing _movej_, worked on a single point buffer.  This means very dense trajectories caused problems due to communication latency (about 40 ms/point).
- Joint stops, safety stops, controller restarts are an issue when moving at high speeds (whether using _servoj_ or _movej_).  It's is still unclear why this is the case.

In addition to speed issues, I also gained some understanding of the current driver design.  A big question for me was why we could not utilize the standard ROS-I clients for the universal.  There are several reasons:
- No support for parsing/encoding floats in URScript
- No support for the controller to be a socket server (can only be a client)
- Limited support for arrays.  2D arrays that could be used for point buffering aren't possible (hence the single point buffer utilized above).

Additional items I should have tried:
- The C-API may solve/avoid many of these issues.  I haven't seen a UR move at full speed using the C-API, but it's hard to believe a lower level driver isn't better.

**Comment by gavanderhoorn** [comment]
So this is a _cant-fix_ or _wont-fix_ for now?

**Comment by shaun-edwards** [comment]
It's a won't fix for now.  After much effort, I was only capable of achieving faster motion by sending less dense trajectories.  I think the C-API needs to be looked into.

**Comment by shaun-edwards** [comment]
Just one final comment.  The branch where I experimented with `movej` commands can be found [here](https://github.com/shaun-edwards/universal_robot/tree/movej_driver).

**Comment by shinian123** [comment]
We encountered this problem recently ,too. I have tried all the methods above ,but still can not solve this problem.Could any one can help us? Thank you!

**Comment by gavanderhoorn** [comment]
Thanks for reporting, but the driver in this repository (`ur_driver`) should not be used any longer. As such, you should report your issue over at [ThomasTimm/ur_modern_driver/issues](https://github.com/ThomasTimm/ur_modern_driver/issues) or [Zagitta/ur_modern_driver/issues](https://github.com/Zagitta/ur_modern_driver/issues).
