### ISSUE TITLE
Exception: Unknown package type: 7

### ISSUE THREAD

**Issue by renauddetry** [ros-industrial/universal_robot#9]
Hello,

I am trying to use my UR5 through ROS with this package, and I cannot make it work. The software on the UR5 is version 1.7.10074. When I launch driver.py, an exception is thrown, then "Waiting to program" is repeatedly printed (see below).

I have not found much information in either the UR wiki or URScript doc on whether anything needs to be done on the robot side to enable remote script execution. At the moment, I simply start the robot and leave it in its default state.

I'd be grateful for any sort of pointer that would help me progress.

Copy of terminal output (ur5 is an alias for 192.168.0.2, the IP of the robot. Pinging ur5 does work):

$ ./driver.py ur5
Setting prefix to 
Disconnected.  Reconnecting
[INFO] [WallTime: 1375956449.773380] Programming the robot
Waiting to program
Exception in thread UR5Connection:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 504, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "./driver.py", line 183, in __run
    self.__on_packet(packet)
  File "./driver.py", line 137, in __on_packet
    state = RobotState.unpack(buf)
  File "/opt/ros/groovy/stacks/universal_robot/ur5_driver/deserialize.py", line 
220, in unpack
    raise Exception("Unknown package type: %i" % ptype)
Exception: Unknown package type: 7
Waiting to program
Waiting to program
Waiting to program

**Comment by shaun-edwards** [comment]
@renauddetry Please post this question on the developers list: swri-ros-pkg-dev@googlegroups.com

I don't think this is a bug and you are more likely to get a response (answer) from that list.  I won't close this issues, just in case it is a bug.

**Comment by renauddetry** [comment]
Hello,

Thanks a lot I'll do that.

**Comment by shaun-edwards** [comment]
This was an issue due to an upgraded UR software version (1.7).  A patch was submitted and accepted.  See pull #11.
