### ISSUE TITLE
Add 'base' coordinate system link to URDFs

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial/universal_robot#95]
As discussed in ros-industrial/ros_industrial_issues#24.

**Comment by gavanderhoorn** [comment]
I've recently done this myself, and I've got values that work. For `base`, only a rotation over Z wrt `base_link` is required, as the meshes in `ur_description` seem to have their origins rotated when compared with the real robot.

Should the meshes perhaps be updated? Then the `base` coordinate frame would be coincidental with `base_link` and things would be much more transparent.

Same goes for `tool0`.

**Comment by fmessmer** [comment]
@abubeck has done this, too....umpf....
Could both of you create PullRequests?

**Comment by gavanderhoorn** [comment]
@ipa-fxm wrote:

> @abubeck has done this, too [..]

I know, I spoke with him, but his branch uses even more rotations. There is only one needed, but even that one can be made unnecessary if we 'fix' the meshes (and thus the orientation of `base_link`).

**Comment by gavanderhoorn** [comment]
#49 (_Add tool0 to URDFs_) is also related.

**Comment by gavanderhoorn** [comment]
I think it would make sense to just rotate the `base_link` link `pi` rad over Z, then rotate the `visual` and `collision` geometry `-pi` to compensate. The `base` frame can then be coincident with `base_link`, no rotations needed anymore.

We can rotate the meshes later then.

**Comment by fmessmer** [comment]
Well, one thing that needs to be considered about your proposed solution is the following:
UR robots are also used in composition with e.g. mobile platforms (e.g. Fraunhofer IPA's rob-@-work) or within environments. They also might exist in composition with tools/grippers attached in ROS. Thus, rotating the base_link in the ur_description will change all those setups!

What we did in @abubeck's solution is add new links `base0` and `tool0` like this:
`base_link` ->TransBase1 -> `base0` ->TransBase2 -> other_ur_links -> TransTool1 -> `tool0` -> TransTool2 -> `arm_ee_link`, where TransXXX are correctly set origins within additional fixed joints....

You can find it [here](https://github.com/abubeck/universal_robot/blob/feature/cartesian_motion/ur_description/urdf/ur5.urdf.xacro)...but I think that file was still rather WIP than final....

However, by "squeezing"-in `base0` and `tool0`, you keep ROS-URDF-compatibility for arms mounted to platforms/environments as well as with endeffectors mounted to the arm while still having the chance to get UR-conform transformations from base0 to tool0 using frames identical with those used within the UR controller!

**Comment by gavanderhoorn** [comment]
I forgot about bw compatibility, you're right.

I do not believe there is any reason to include `base` and `tool0` in the kinematic chain though. `tool0` will probably be the tip of the chain but doesn't have to be (to maintain bw compat again), and `base` can be an extra leaf frame, child of `base_link`. That is how it has been done in all other ros-i support pkgs.

```
base_link -> rest_of_chain -> wrist_3_link -> ee_link
|                             |
 -> base                       -> tool0
```

That should keep everything bw compat, while adding the new frames in the places where they should be with the proper orientations. We would also not have to update the MoveIt configs like this.

I do still believe that the meshes will have to be fixed though, but that is something that can then be done in K-turtle fi.

**Comment by gavanderhoorn** [comment]
See also #80.

**Comment by fmessmer** [comment]
done in #200. closing.
